Face web scraping do forecasts da pagina  https://www.forecasts.org/all-forecasts.htm

gera df con os títulos ao consultar (symbol , url)

In [5]:
import sqlite3
import pandas as pd

# Conectar ao banco de dados SQLite
conn = sqlite3.connect("sqforecasts.db")

# Criar a consulta SQL
query = "SELECT id_titulos, symbol, url FROM tbtitulos"

# Criar o DataFrame com os dados da consulta
dftitulos = pd.read_sql(query, conn)

# Fechar a conexão
conn.close()

# Exibir o DataFrame
display(dftitulos)

   id_titulos   symbol                                            url
0           1      DXY  https://www.forecasts.org/dollar-forecast.htm
1           2    US10Y            https://www.forecasts.org/10yrT.htm
2           3     USIR        https://www.forecasts.org/inflation.htm
3           4      SPX           https://www.forecasts.org/stpoor.htm
4           5  EUR/USD             https://www.forecasts.org/euro.htm

In [54]:
# Selecionando um id específico
id_especifico = 2  # Alterar para o ID desejado

In [56]:
import pandas as pd
dftituloselec = dftitulos[dftitulos["id_titulos"] == id_especifico]
dftituloselec.columns = dftituloselec.columns.str.strip()  # Remove espaços nos nomes das colunas
# Definir a url 
url=(dftituloselec['url'].iloc[0]) #define a url para a função get_fore_dados(url)
id_titulos= int(dftituloselec['id_titulos'].iloc[0])
print(dftituloselec)
print(url)
print(id_titulos)

   id_titulos symbol                                  url
1           2  US10Y  https://www.forecasts.org/10yrT.htm
https://www.forecasts.org/10yrT.htm
2

Extrae com a url selecionada a tabula com os dados de forecast com a função
get_fore_dados(url) return: df_forecasts_scrap, updated_date

In [84]:
# Função para obter os dados do índice
def get_fore_dados(url):
    import requests
    import pandas as pd
    from bs4 import BeautifulSoup
    # Fazer a requisição HTTP para a página
    response = requests.get(url)
    response.raise_for_status()  # Verifica se houve erro na requisição

    # Criar o objeto BeautifulSoup para processar o HTML
    soup = BeautifulSoup(response.text, "html.parser")

    # Localizar a tabela pelo ID (caso tenha um identificador)
    table = soup.find("table", {"id": "forecast"})
    
    # Extrair todas as linhas da tabela
    rows = table.find_all("tr")[1:]  # Ignora o cabeçalho

    # Criar lista para armazenar os dados extraídos
    data_list = []
    
    for row in rows:
        cols = row.find_all("td")
        month = cols[1].text.strip()
        date = pd.to_datetime(month)  # Convertendo a string para uma data válida
        forecast_value = float(cols[2].text.strip())
        avg_error = float(cols[3].text.replace("±", "").strip())

        data_list.append([month, date, forecast_value, avg_error])

    # Criar DataFrame
    df_forecasts_scrap = pd.DataFrame(data_list, columns=["Month", "Date", "Forecast Value", "Avg Error"])

    # --- Capturar a data de atualização ---
    updated_text = soup.find("time").text.strip()
    updated_date = pd.to_datetime(updated_text.replace("Updated: ", ""))  # Converter para formato datetime

    return df_forecasts_scrap, updated_date

# Chamar a função para obter os dados
df_forecasts_scrap, last_updated = get_fore_dados(url)

In [86]:

# Exibir os dados
display(f"idtitulos:{id_titulos}")
display(f"Última atualização: {last_updated}")
display(df_forecasts_scrap.columns)
display(df_forecasts_scrap)

'idtitulos:2'

'Última atualização: 2025-05-15 00:00:00'

Index(['Month', 'Date', 'Forecast Value', 'Avg Error'], dtype='object')

      Month       Date  Forecast Value  Avg Error
0  Apr 2025 2025-04-01            4.28      0.000
1  May 2025 2025-05-01            4.40      0.078
2  Jun 2025 2025-06-01            4.29      0.100
3  Jul 2025 2025-07-01            4.04      0.110
4  Aug 2025 2025-08-01            3.78      0.120
5  Sep 2025 2025-09-01            3.16      0.130
6  Oct 2025 2025-10-01            2.97      0.140
7  Nov 2025 2025-11-01            2.99      0.140
8  Dec 2025 2025-12-01            2.64      0.150

Insere na tabela tbforecasts (si no existe registro) um novo e devolve os valores: existsforecast e
id_forecastins com a função insere_forecast(id_titulos, data) return id_forecastins, existsforecast

In [64]:
import sqlite3
def insere_forecast(id_titulos,data):
    # Conectar ao banco de dados SQLite
    conn = sqlite3.connect("sqforecasts.db")
    cursor = conn.cursor()
    
    # Verificar se o registro já existe
    cursor.execute("SELECT COUNT(*) FROM tbforecasts WHERE id_titulos = ? AND data = ?", (id_titulos, str(data)))
    existsforecast= cursor.fetchone()[0]
    
    # Se não existir, inserir o novo registro
    if existsforecast ==  0 :
        cursor.execute("INSERT INTO tbforecasts (id_titulos, data) VALUES (?, ?)", (id_titulos, str(data)))
        conn.commit()
        print("Registro inserido com sucesso!")
        # Valor do id do registro inserido
        id_forecastins = cursor.lastrowid 
    else:
        id_forecastins = 0
    # Fechar conexão
    conn.close()
    return id_forecastins, existsforecast

id_forecastins, existsforecast = insere_forecast(id_titulos,last_updated)

Registro inserido com sucesso!

In [66]:
if existsforecast ==0:
    print (f'existsforecast:{ existsforecast} registro inserido')
    print (f'id_forecastins:{id_forecastins} ultimo id')
else:
    print (f'existsforecast:{ existsforecast} el registro ja existe')
    print (f'id_forecastins:{id_forecastins} no se gero id')

existsforecast:0 registro inserido
id_forecastins:11 ultimo id

Si existforecast = 0 Crea o registro para inserir em na tabela tbtituloshist
tituloshist_reg(df_forecast_scrap)
return dftituloshistins

In [69]:
import pandas as pd

# Valores do DataFrame original
primeiro_date = str(df_forecasts_scrap["Date"].iloc[0])  # Pegando o primeiro valor de Date
primeiro_forecast_value = float(df_forecasts_scrap["Forecast Value"].iloc[0])  # Pegando o primeiro valor de Forecast Value

# Criando o novo DataFrame
dftituloshistins = pd.DataFrame({
    "id_titulos": [id_titulos],
    "data": [primeiro_date],
    "valor": [primeiro_forecast_value]
})

display(dftituloshistins)

   id_titulos                 data  valor
0           2  2025-04-01 00:00:00   4.28

Insere registro e verifica que no este duplicado
forecasthist_insere (dftituloshistins)
return existshist

In [72]:
import sqlite3

def forecasthist_insere (dftituloshistins):
    # Conectar ao banco de dados SQLite
    conn = sqlite3.connect("sqforecasts.db")
    cursor = conn.cursor()
    
    # Definir os valores
    id_titulos = (dftituloshistins["id_titulos"].iloc[0]) 
    data = (dftituloshistins["data"].iloc[0]) 
    valor = (dftituloshistins["valor"].iloc[0]) 
    
    # Verificar se o registro já existe
    cursor.execute("SELECT COUNT(*) FROM tbtituloshist WHERE id_titulos = ? AND data = ?", (id_titulos, data))
    existshist = cursor.fetchone()[0]
    
    # Se não existir, inserir o novo registro
    if existshist == 0:
        cursor.execute("INSERT INTO tbtituloshist (id_titulos, data, valor) VALUES (?, ?, ?)", (id_titulos, data, valor))
        conn.commit()
        
    else:
        existshist = 1
    # Fechar conexão
    conn.close()
    return existshist
existshist = forecasthist_insere(dftituloshistins)

In [74]:
print (f'existshist:{ existshist}')

existshist:1

creo dfforecastdadosins para inserir os dados na tabela dfforecastdados solo si existforecast = 0

In [77]:
# Criando o novo DataFrame
dfforecastsdados = pd.DataFrame({
    
    "id_forecasts":  [int(id_forecastins)] * len(df_forecasts_scrap),
    "data": df_forecasts_scrap['Date'], 
    "valor": df_forecasts_scrap['Forecast Value'],
    "error": df_forecasts_scrap['Avg Error'] ,
})
display (dfforecastsdados)

   id_forecasts       data  valor  error
0            11 2025-04-01   4.28  0.000
1            11 2025-05-01   4.40  0.078
2            11 2025-06-01   4.29  0.100
3            11 2025-07-01   4.04  0.110
4            11 2025-08-01   3.78  0.120
5            11 2025-09-01   3.16  0.130
6            11 2025-10-01   2.97  0.140
7            11 2025-11-01   2.99  0.140
8            11 2025-12-01   2.64  0.150

In [80]:
import sqlite3
import pandas as pd

def forecastsdados_insere (dfforecastsdados):
    # Conectar ao banco de dados
    conn = sqlite3.connect('sqforecasts.db')
    cursor = conn.cursor()
    
    # Obter IDs existentes na tabela
    cursor.execute("SELECT DISTINCT id_forecasts FROM tbforecastsdados")
    ids_existentes = {row[0] for row in cursor.fetchall()}  # Converte para conjunto (set) para busca rápida
    
    # Filtrar o DataFrame: manter apenas registros cujo id_forecasts não está na tabela
    dfforecastsdados_filtrado = dfforecastsdados[~dfforecastsdados['id_forecasts'].isin(ids_existentes)]
    
    # Verificar se há dados para inserir
    if not dfforecastsdados_filtrado.empty:
        # Inserir os dados filtrados no SQLite
        dfforecastsdados_filtrado.to_sql('tbforecastsdados', conn, if_exists='append', index=False)
        existsforecastsdados = 0
    else:
        existsforecastsdados = 1          
    # Fechar a conexão com o banco
    conn.close()
    return existsforecastsdados
existsforecastsdados = forecastsdados_insere (dfforecastsdados)

In [82]:
if existsforecastsdados == 0 :
    print("Dados inseridos em tbforecastsdados com sucesso!")
else:
    print("Nenhum dado novo para inserir em tbforecastsdados.")

Dados inseridos em tbforecastsdados com sucesso!