Back Testing

In [198]:
from datetime import date, datetime
import pandas as pd
import yfinance as yf
import time
from Alert import Alert
pd.options.mode.chained_assignment = None  # default='warn'
alert = Alert('1h','GGAL')

In [ ]:
input:
    
     Titulo  : example: GGAL
     frequencia de tick : 1h (frequencia mais alta)
     dftitulo : vista do BD sqtitulosalpha.bd (testar ultimos periodas)
Parametros a variar para back testing ( definir rangos de variação)
     k, d, smooth (parametros do stch)
     dayM  (frequencia media) (multiplicador da frequencia mais alta) exemplo: 5
     semM  (frequencia baixa) (multiplicador da frequencia media) exemplo: 7

In [137]:
dataini = '2020-04-03 19:30:00'
datafim = '2023-04-03 19:30:00'

In [156]:
import sqlite3
import pandas as pd

# Caminho para o banco de dados
caminho_bd = r'C:\Users\scitr\anaconda_projects\Trading_System\Dados_Fontes\Alpha_Vantage\sqtitulosalpha.db'

# Conectando ao banco
conexao = sqlite3.connect(caminho_bd)

# Lendo a view
#consulta = 'SELECT * FROM vwtitulosdados ORDER BY datetime'
consulta = f"""
SELECT * FROM vwtitulosdados
WHERE datetime BETWEEN '{dataini}' AND '{datafim}'
ORDER BY datetime
"""

dftitulosdados = pd.read_sql_query(consulta, conexao)

# Fechando a conexão
conexao.close()

# Exibindo os primeiros registros para conferir
display(dftitulosdados)

,symbol,moeda,intervalo,datetime,open,high,low,close,volume
0,GGAL,USD,60min,2020-04-06 08:00:00,5.8034,5.8034,5.8034,5.8034,100.0
1,GGAL,USD,60min,2020-04-06 09:00:00,6.0432,6.2510,5.9952,6.0832,114582.0
2,GGAL,USD,60min,2020-04-06 10:00:00,6.0945,6.0945,5.6635,5.7954,159266.0
3,GGAL,USD,60min,2020-04-06 11:00:00,5.7954,5.8034,5.4837,5.6835,242263.0
4,GGAL,USD,60min,2020-04-06 12:00:00,5.6715,5.8354,5.6355,5.8274,186504.0
...,...,...,...,...,...,...,...,...,...
6578,GGAL,USD,60min,2023-04-03 12:00:00,9.5499,9.6357,9.5499,9.5756,29258.0
6579,GGAL,USD,60min,2023-04-03 13:00:00,9.5671,9.6872,9.5671,9.6700,48527.0
6580,GGAL,USD,60min,2023-04-03 14:00:00,9.6785,9.7447,9.6529,9.7301,32877.0
6581,GGAL,USD,60min,2023-04-03 15:00:00,9.7386,9.7816,9.6529,9.7558,143309.0
6582,GGAL,USD,60min,2023-04-03 16:00:00,9.7472,9.7472,9.7472,9.7472,13155.0

In [158]:

i = '1h'
K = 16  
D = 5    
smoth = 5  
dayM = 8  
semM = 4

In [160]:
# Stochastic calculation
def stochastic(df, i, K, D, smoth):
        
    df["k"] = (100. * (df.close - df.low.rolling(K).min()) /
        (df.high.rolling(K).max() - df.low.rolling(K).min()))
    
    df["k" + i] = df.k.rolling(smoth).mean()
    df["d" + i] = df["k" + i].rolling(D).mean()
    
    df.drop(columns=["k"], inplace=True)  

    return df
dfstoch = stochastic(dftitulosdados, i, K, D, smoth)
display (dfstoch)

,symbol,moeda,intervalo,datetime,open,high,low,close,volume,k1h,d1h
0,GGAL,USD,60min,2020-04-06 08:00:00,5.8034,5.8034,5.8034,5.8034,100.0,NaN,NaN
1,GGAL,USD,60min,2020-04-06 09:00:00,6.0432,6.2510,5.9952,6.0832,114582.0,NaN,NaN
2,GGAL,USD,60min,2020-04-06 10:00:00,6.0945,6.0945,5.6635,5.7954,159266.0,NaN,NaN
3,GGAL,USD,60min,2020-04-06 11:00:00,5.7954,5.8034,5.4837,5.6835,242263.0,NaN,NaN
4,GGAL,USD,60min,2020-04-06 12:00:00,5.6715,5.8354,5.6355,5.8274,186504.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
6578,GGAL,USD,60min,2023-04-03 12:00:00,9.5499,9.6357,9.5499,9.5756,29258.0,35.345039,24.486408
6579,GGAL,USD,60min,2023-04-03 13:00:00,9.5671,9.6872,9.5671,9.6700,48527.0,43.814248,30.270650
6580,GGAL,USD,60min,2023-04-03 14:00:00,9.6785,9.7447,9.6529,9.7301,32877.0,53.958531,37.149336
6581,GGAL,USD,60min,2023-04-03 15:00:00,9.7386,9.7816,9.6529,9.7558,143309.0,64.423364,45.395125
6582,GGAL,USD,60min,2023-04-03 16:00:00,9.7472,9.7472,9.7472,9.7472,13155.0,69.770972,53.462431

In [165]:
def set_test( df, intervalo, k, d, smth, dayM, semM):
        
        # Convert time
        #df["time"] = pd.to_datetime(df.index, utc=True)
        #df['timeArg'] = df['time'].dt.tz_convert('America/Argentina/Buenos_Aires')        
        #df['time'] = df['time'].dt.tz_convert(None)

        df = stochastic(df, "hora", k, d, smth)
        df = stochastic(df, "dia", k*dayM, d*dayM, smth*dayM)
        df = stochastic(df, "sem", k*dayM*semM, d*dayM*semM, smth*dayM*semM)
    
        return df
dfstochhlc= set_test(dfstoch, i , K, D, smoth, dayM , semM )
display(dfstochhlc )
%time set_test(dfstoch, i , K, D, smoth, dayM , semM )

,symbol,moeda,intervalo,datetime,open,high,low,close,volume,k1h,d1h,khora,dhora,kdia,ddia,ksem,dsem
0,GGAL,USD,60min,2020-04-06 08:00:00,5.8034,5.8034,5.8034,5.8034,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,GGAL,USD,60min,2020-04-06 09:00:00,6.0432,6.2510,5.9952,6.0832,114582.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,GGAL,USD,60min,2020-04-06 10:00:00,6.0945,6.0945,5.6635,5.7954,159266.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,GGAL,USD,60min,2020-04-06 11:00:00,5.7954,5.8034,5.4837,5.6835,242263.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,GGAL,USD,60min,2020-04-06 12:00:00,5.6715,5.8354,5.6355,5.8274,186504.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6578,GGAL,USD,60min,2023-04-03 12:00:00,9.5499,9.6357,9.5499,9.5756,29258.0,35.345039,24.486408,35.345039,24.486408,45.055766,33.328487,48.012866,70.547223
6579,GGAL,USD,60min,2023-04-03 13:00:00,9.5671,9.6872,9.5671,9.6700,48527.0,43.814248,30.270650,43.814248,30.270650,45.854905,33.918139,47.710336,70.311149
6580,GGAL,USD,60min,2023-04-03 14:00:00,9.6785,9.7447,9.6529,9.7301,32877.0,53.958531,37.149336,53.958531,37.149336,46.699935,34.512110,47.428408,70.073438
6581,GGAL,USD,60min,2023-04-03 15:00:00,9.7386,9.7816,9.6529,9.7558,143309.0,64.423364,45.395125,64.423364,45.395125,47.601915,35.110265,47.142843,69.834096
6582,GGAL,USD,60min,2023-04-03 16:00:00,9.7472,9.7472,9.7472,9.7472,13155.0,69.770972,53.462431,69.770972,53.462431,48.490496,35.712189,46.851390,69.593059

CPU times: total: 31.2 ms
Wall time: 34.3 ms

,symbol,moeda,intervalo,datetime,open,high,low,close,volume,k1h,d1h,khora,dhora,kdia,ddia,ksem,dsem
0,GGAL,USD,60min,2020-04-06 08:00:00,5.8034,5.8034,5.8034,5.8034,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,GGAL,USD,60min,2020-04-06 09:00:00,6.0432,6.2510,5.9952,6.0832,114582.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,GGAL,USD,60min,2020-04-06 10:00:00,6.0945,6.0945,5.6635,5.7954,159266.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,GGAL,USD,60min,2020-04-06 11:00:00,5.7954,5.8034,5.4837,5.6835,242263.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,GGAL,USD,60min,2020-04-06 12:00:00,5.6715,5.8354,5.6355,5.8274,186504.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6578,GGAL,USD,60min,2023-04-03 12:00:00,9.5499,9.6357,9.5499,9.5756,29258.0,35.345039,24.486408,35.345039,24.486408,45.055766,33.328487,48.012866,70.547223
6579,GGAL,USD,60min,2023-04-03 13:00:00,9.5671,9.6872,9.5671,9.6700,48527.0,43.814248,30.270650,43.814248,30.270650,45.854905,33.918139,47.710336,70.311149
6580,GGAL,USD,60min,2023-04-03 14:00:00,9.6785,9.7447,9.6529,9.7301,32877.0,53.958531,37.149336,53.958531,37.149336,46.699935,34.512110,47.428408,70.073438
6581,GGAL,USD,60min,2023-04-03 15:00:00,9.7386,9.7816,9.6529,9.7558,143309.0,64.423364,45.395125,64.423364,45.395125,47.601915,35.110265,47.142843,69.834096
6582,GGAL,USD,60min,2023-04-03 16:00:00,9.7472,9.7472,9.7472,9.7472,13155.0,69.770972,53.462431,69.770972,53.462431,48.490496,35.712189,46.851390,69.593059

In [168]:
#insere  'COMPRA' no campo oper do df no registro i 
def set_compra( df, i):
        df.loc[i, "oper"] = "COMPRA"
    
#insere  'VENTA' no campo oper do df no registro i 
def set_venta( df, i):
        df.loc[i, "oper"] = "VENTA"


def close_long( df, i, compra, venta):
        df.loc[i, "oper"] = "CLOSELONG"
        if compra !=0.:
            df.loc[i, "long"] = (venta - compra) / compra


def close_short( df, i, compra, venta):
        df.loc[i, "oper"] = "CLOSESHORT"
        if venta !=0.:
            df.loc[i, "short"] = (venta - compra) / venta

In [170]:
def set_signals(df):
        state = ""
        df["compra"] = False
        df["venta"] = False
        df["closeLong"] = False
        df["closeShort"] = False
        df["entradaLongH"] = False
        df["entradaShortH"] = False
        df["oper"] = ""
        df["long"] = ""
        df["short"] = ""
        df["state"] = "neutro"

        compra = 0.
        venta = 0.
#alert.py part 2
        
# outros intervalos
        lastEntradaLongH = False
        lastEntradaShortH = False
            
        for i in df.index:      
            l = df.loc[i]
            df.loc[i, "state"] = state

        #for i, l in df.iterrows():
            #df.at[i, "state"] = state
            khora = float(l.khora)
            dhora = float(l.dhora)
            kdia = float(l.kdia)
            ddia = float(l.ddia)
            ksem = float(l.ksem)
            dsem = float(l.dsem)
            
            if (khora > 20) and (khora > dhora):                   # "si stoch high EM CONDIÇÃO DE COMPRA          
                    df.at[i, "entradaLongH"] = True     
        
                # ESTRATEGIA 1 - Stochastico alineado y esperar cruce
                #if (l.khora > 20. and l.khora > l.dhora):
                    #df.loc[i, "entradaLongH"] = True
                    if (not lastEntradaLongH):                       # si  la entradalong anterior es true  
                        if (kdia > 20. and kdia > ddia):                 # si stch midfre em condição de compra
                            if(state == "venta"):                           # si estabamos en short 
                                df.loc[i, "closeShort"] = True                 # fechamos short
                                state = "neutro"                               # mudamos estado a neutro
                                compra = l.close                               
                                close_short(df, i, compra, venta)              # calcula ganancia porcentual y coloca na coluna short
                            if (ksem > 80. or ksem > dsem):                  #stch lowfre acima media d ou acima de 80 , para evitar saida anticipada
                                df.loc[i, "compra"] = True                       # compramos long                  
                                if state != "compra":                             # si no tenihamos comprado
                                    state = "compra"                                 # mudamos estado a compra
                                    compra = l.close                                 
                                    set_compra(df, i)                                # mudamos oper a COMPRA
            else:
                df.loc[i, "entradaLongH"] = False                   # si no esta  em condição de compra 

            if (l.khora < 80. and l.khora < l.dhora):
                    df.loc[i, "entradaShortH"] = True
                    if (not lastEntradaShortH):
                        if(l.kdia < 80. and l.kdia < l.ddia):
                            if(state == "compra"):
                                df.loc[i, "closeLong"] = True
                                state = "neutro"
                                venta = l.close
                                close_long(df, i, compra, venta)
                            if(l.ksem < 20. or l.ksem < l.dsem):
                                df.loc[i, "venta"] = True
                                if state != "venta":
                                    state = "venta"
                                    venta = l.close
                                    set_venta(df, i)
            else:
                    df.loc[i, "entradaShortH"] = False

            lastEntradaLongH = df.loc[i, "entradaLongH"]
            lastEntradaShortH = df.loc[i, "entradaShortH"]
                    
        
        return df
    
dfsignal= set_signals(dfstochhlc)          
#display(dfsignal)

In [194]:
#df_filtrado = dfsignal[dfsignal['compra'].notna() | dfsignal['venta'].notna()]
#df_filtrado = dfsignal[dfsignal['state'].notna()]
df_filtrado = dfsignal[(dfsignal['state'].notna()) & (dfsignal['state'] == 'venta')]
#df_filtrado = dfsignal[dfsignal['compra'] == True]
df_filtrado = dfsignal[dfsignal['oper'] != '']

pd.set_option('display.max_rows', None)  # Mostra todas as linhas

print(f"Total de registros com 'state' preenchido: {len(df_filtrado)}")
display(df_filtrado.iloc[:, 11:])

Total de registros com 'state' preenchido: 87

,khora,dhora,kdia,ddia,ksem,dsem,compra,venta,closeLong,closeShort,entradaLongH,entradaShortH,oper,long,short,state
719,58.805532,54.782934,77.560404,69.456308,84.667712,NaN,True,False,False,False,True,False,COMPRA,,,
767,56.570574,66.085405,66.369308,78.457399,86.460965,NaN,False,False,True,False,False,True,CLOSELONG,-0.069267,,compra
846,6.715225,6.755678,30.931970,48.482412,79.710350,84.534459,False,True,False,False,False,True,VENTA,,,neutro
970,43.816521,43.814087,21.067897,12.366351,33.094373,62.534045,False,False,False,True,True,False,CLOSESHORT,,0.081937,venta
1060,51.218447,51.755551,24.412361,40.063877,15.071505,32.399684,False,True,False,False,False,True,VENTA,,,neutro
1195,27.500680,17.702370,20.897295,17.598614,4.512878,10.439022,False,False,False,True,True,False,CLOSESHORT,,0.199556,venta
1258,13.224721,14.984595,25.773712,30.182975,4.880179,6.585868,False,True,False,False,False,True,VENTA,,,neutro
1299,27.344972,15.490774,28.014453,23.058807,4.739077,5.355476,False,False,False,True,True,False,CLOSESHORT,,-0.029422,venta
1325,59.038095,65.853663,25.329733,27.756764,4.365731,4.901127,False,True,False,False,False,True,VENTA,,,neutro
1368,86.525592,86.279734,34.938730,25.590686,4.898888,4.620799,True,False,False,True,True,False,COMPRA,,-0.048343,venta
1459,72.435984,79.153232,79.224264,83.336733,26.703526,9.924836,False,False,True,False,False,True,CLOSELONG,0.190193,,compra
1521,63.571611,62.461801,75.254779,74.311003,45.994521,22.341196,True,False,False,False,True,False,COMPRA,,,neutro
1594,32.264328,45.979869,74.517188,81.905040,66.096173,43.645044,False,False,True,False,False,True,CLOSELONG,-0.014733,,compra
1699,52.857762,51.492607,36.172250,33.800972,83.550640,70.847190,True,False,False,False,True,False,COMPRA,,,neutro
1745,47.970770,50.260151,32.978615,46.763865,80.334349,77.883162,False,False,True,False,False,True,CLOSELONG,-0.069419,,compra
1771,25.962928,27.996971,13.878475,26.934784,76.744760,79.761051,False,True,False,False,False,True,VENTA,,,neutro
1873,62.494030,60.525532,21.583904,10.942217,58.010069,72.905157,False,False,False,True,True,False,CLOSESHORT,,0.011395,venta
1986,75.918055,82.515381,74.510173,75.405037,39.702871,51.050077,False,True,False,False,False,True,VENTA,,,neutro
1996,67.026236,62.696431,78.609674,75.638443,40.295718,49.325586,False,False,False,True,True,False,CLOSESHORT,,-0.03975,venta
2029,12.850684,17.712793,73.521941,80.744371,44.102230,45.162125,False,True,False,False,False,True,VENTA,,,neutro
2158,81.038417,80.334915,23.144059,10.576499,27.380491,39.844754,False,False,False,True,True,False,CLOSESHORT,,0.021252,venta
2228,74.121017,77.864241,63.941543,69.807392,26.034093,31.525079,False,True,False,False,False,True,VENTA,,,neutro
2316,25.724382,22.670074,32.092717,30.283210,36.159389,28.426327,True,False,False,True,True,False,COMPRA,,0.021496,venta
2350,76.347946,76.586137,21.435346,29.225406,30.717154,30.265600,False,False,True,False,False,True,CLOSELONG,-0.052963,,compra
2478,60.067058,62.916389,29.952618,47.067776,17.595251,25.131625,False,True,False,False,False,True,VENTA,,,neutro
2512,29.138545,27.671929,55.976029,36.399338,21.310451,22.045283,False,False,False,True,True,False,CLOSESHORT,,-0.085764,venta
2522,22.314866,16.708310,63.822826,43.942568,22.879028,21.599748,True,False,False,False,True,False,COMPRA,,,neutro
2594,24.589182,25.346753,78.509835,83.328001,50.472288,27.744432,False,False,True,False,False,True,CLOSELONG,0.05998,,compra
2630,83.586016,82.295569,74.907693,73.709935,63.934951,35.711149,True,False,False,False,True,False,COMPRA,,,neutro
2741,79.873711,80.623880,79.800686,84.383598,86.174426,72.729001,False,False,True,False,False,True,CLOSELONG,0.150907,,compra
2809,48.595705,50.419036,27.137115,41.376530,81.407383,84.390744,False,True,False,False,False,True,VENTA,,,neutro
2968,30.620037,12.570999,30.957591,19.859187,35.954366,57.278656,False,False,False,True,True,False,CLOSESHORT,,0.100938,venta
3018,18.865373,19.564840,28.529124,36.605976,28.897159,44.212289,False,True,False,False,False,True,VENTA,,,neutro
3045,74.640110,71.239340,28.825663,27.525494,25.734603,38.460028,False,False,False,True,True,False,CLOSESHORT,,-0.068561,venta
3108,26.626336,32.057637,73.675011,74.531119,22.122637,28.583588,False,True,False,False,False,True,VENTA,,,neutro
3157,95.660989,95.042016,82.887564,66.061092,25.532670,24.470705,True,False,False,True,True,False,COMPRA,,-0.210576,venta
3287,13.144831,15.518698,65.396752,78.194817,76.836773,47.663538,False,False,True,False,False,True,CLOSELONG,0.079532,,compra
3365,67.496299,78.059553,5.900624,10.067825,63.392672,68.409220,False,True,False,False,False,True,VENTA,,,neutro
3409,46.320982,37.458088,26.189380,13.708260,52.559421,68.780297,False,False,False,True,True,False,CLOSESHORT,,-0.091968,venta
3525,36.201705,31.839211,88.635984,87.496112,53.028702,50.553226,True,False,False,False,True,False,COMPRA,,,neutro
3563,29.085409,30.465867,74.968811,86.249716,59.495721,50.208378,False,False,True,False,False,True,CLOSELONG,-0.040249,,compra
3609,39.070620,38.794844,53.251779,49.681131,63.859629,53.638410,True,False,False,False,True,False,COMPRA,,,neutro
3660,30.412462,32.970999,74.063248,77.030694,70.735902,60.824742,False,False,True,False,False,True,CLOSELONG,-0.002631,,compra
3694,38.589177,43.750367,20.656160,49.854801,61.980624,64.153792,False,True,False,False,False,True,VENTA,,,neutro
3788,76.917799,73.988103,22.794539,12.951451,28.206750,54.305728,False,False,False,True,True,False,CLOSESHORT,,0.018269,venta
4000,77.518871,72.769679,31.307723,28.551964,25.916885,23.271487,True,False,False,False,True,False,COMPRA,,,neutro
4029,22.745605,23.103032,28.479921,31.458789,24.628421,24.743533,False,True,True,False,False,True,VENTA,-0.076055,,compra
4080,50.024335,34.041512,28.023280,15.617497,18.722072,24.471271,False,False,False,True,True,False,CLOSESHORT,,-0.023364,venta
4139,22.294380,13.879640,82.832490,77.265123,22.438387,22.205219,True,False,False,False,True,False,COMPRA,,,neutro
4165,29.485071,30.380233,75.666033,81.229443,24.120399,21.845707,False,False,True,False,False,True,CLOSELONG,-0.002148,,compra
4225,80.635215,74.107681,67.321442,64.841118,39.374078,24.441440,True,False,False,False,True,False,COMPRA,,,neutro
4261,77.014152,77.136039,73.673755,74.882556,51.189611,30.539255,False,False,True,False,False,True,CLOSELONG,-0.004946,,compra
4364,21.358232,15.486708,66.027045,52.277968,71.439892,54.575774,True,False,False,False,True,False,COMPRA,,,neutro
4462,68.682325,69.731198,78.184429,81.404953,81.346987,72.044855,False,False,True,False,False,True,CLOSELONG,0.087652,,compra
4555,67.186667,67.644820,28.003812,41.416411,81.152019,81.768102,False,True,False,False,False,True,VENTA,,,neutro
4660,85.277715,83.505813,22.196986,15.237251,41.938359,71.160514,False,False,False,True,True,False,CLOSESHORT,,0.076,venta
4704,76.143440,85.039721,17.619363,20.092874,26.412233,57.008014,False,True,False,False,False,True,VENTA,,,neutro
4711,70.198842,68.963804,21.112599,19.679058,24.502589,54.517263,False,False,False,True,True,False,CLOSESHORT,,-0.034163,venta
4774,70.484574,72.717531,72.079071,74.487398,24.710704,33.869068,False,True,False,False,False,True,VENTA,,,neutro
4800,63.958569,61.133329,75.225236,72.682171,29.256724,29.079653,True,False,False,True,True,False,COMPRA,,-0.032574,venta
4821,7.776801,8.131000,73.701465,74.476363,32.356043,27.255890,False,False,True,False,False,True,CLOSELONG,-0.053625,,compra
4900,16.707825,23.332881,4.619167,12.966947,29.509521,30.248840,False,True,False,False,False,True,VENTA,,,neutro
5130,91.360032,90.660868,22.928019,17.648799,6.268857,6.291502,False,False,False,True,True,False,CLOSESHORT,,0.086613,venta
5141,72.173900,67.738578,37.136539,20.912819,7.331500,5.923895,True,False,False,False,True,False,COMPRA,,,neutro
5314,76.086495,85.654164,73.685357,80.608475,56.374595,33.452976,False,False,True,False,False,True,CLOSELONG,0.258941,,compra
5336,66.791340,66.202705,86.996274,76.700042,60.239181,39.698281,True,False,False,False,True,False,COMPRA,,,neutro
5381,76.787086,81.449106,60.446742,74.124837,68.428201,51.499929,False,False,True,False,False,True,CLOSELONG,-0.018185,,compra
5402,47.358960,44.994445,74.017601,64.830260,73.728196,56.614391,True,False,False,False,True,False,COMPRA,,,neutro
5435,35.270385,36.165068,73.022467,77.588095,78.634958,63.985283,False,False,True,False,False,True,CLOSELONG,0.008051,,compra
5515,23.328658,26.225267,13.151245,36.282045,76.005432,76.140593,False,True,False,False,False,True,VENTA,,,neutro
5566,25.462687,17.997773,32.745753,19.995132,64.882332,76.726726,False,False,False,True,True,False,CLOSESHORT,,-0.058511,venta
5585,28.211485,32.252581,29.169720,29.909186,60.400668,75.066320,False,True,False,False,False,True,VENTA,,,neutro
5633,33.871703,32.536619,20.154836,16.953589,48.752888,67.331696,False,False,False,True,True,False,CLOSESHORT,,0.006676,venta
5749,42.073565,45.231127,66.316135,73.564460,32.887713,44.305146,False,True,False,False,False,True,VENTA,,,neutro
5846,92.233148,92.130712,28.746121,17.380236,19.332308,29.908889,False,False,False,True,True,False,CLOSESHORT,,-0.003887,venta
5917,68.790491,85.678333,68.285399,81.178857,22.032197,22.946808,False,True,False,False,False,True,VENTA,,,neutro
5989,85.352290,84.958913,56.610652,48.274519,33.133073,22.628551,True,False,False,True,True,False,COMPRA,,-0.119745,venta
6172,78.748021,85.785511,79.064559,88.071300,93.295182,74.121458,False,False,True,False,False,True,CLOSELONG,0.584197,,compra
6212,21.413197,12.381936,82.748263,81.902632,92.268810,84.454837,True,False,False,False,True,False,COMPRA,,,neutro
6228,55.952378,58.960314,72.432461,81.698594,91.266980,87.491597,False,False,True,False,False,True,CLOSELONG,-0.003843,,compra
6252,5.978593,6.845766,51.663323,67.927950,88.814017,90.461543,False,True,False,False,False,True,VENTA,,,neutro
6307,92.750810,92.679638,47.124022,39.384747,84.041986,89.936630,True,False,False,True,True,False,COMPRA,,-0.149595,venta
6361,75.749391,76.562235,61.143755,68.568676,84.660759,87.246360,False,True,True,False,False,True,VENTA,-0.042439,,compra
6390,20.893403,14.399201,59.579618,58.934919,85.367263,85.974137,True,False,False,True,True,False,COMPRA,,0.010484,venta
6420,71.576742,82.036825,34.405540,50.870931,85.462191,85.164868,False,False,True,False,False,True,CLOSELONG,-0.058064,,compra
6460,22.931667,25.775928,19.766555,26.189284,83.324777,85.058824,False,True,False,False,False,True,VENTA,,,neutro
6552,89.547760,88.964905,28.591524,21.207692,54.815290,76.013981,False,False,False,True,True,False,CLOSESHORT,,-0.032389,venta

In [171]:
%time set_signals(dfstochhlc)

CPU times: total: 11 s
Wall time: 11.3 s

,symbol,moeda,intervalo,datetime,open,high,low,close,volume,k1h,...,compra,venta,closeLong,closeShort,entradaLongH,entradaShortH,oper,long,short,state
0,GGAL,USD,60min,2020-04-06 08:00:00,5.8034,5.8034,5.8034,5.8034,100.0,NaN,...,False,False,False,False,False,False,,,,
1,GGAL,USD,60min,2020-04-06 09:00:00,6.0432,6.2510,5.9952,6.0832,114582.0,NaN,...,False,False,False,False,False,False,,,,
2,GGAL,USD,60min,2020-04-06 10:00:00,6.0945,6.0945,5.6635,5.7954,159266.0,NaN,...,False,False,False,False,False,False,,,,
3,GGAL,USD,60min,2020-04-06 11:00:00,5.7954,5.8034,5.4837,5.6835,242263.0,NaN,...,False,False,False,False,False,False,,,,
4,GGAL,USD,60min,2020-04-06 12:00:00,5.6715,5.8354,5.6355,5.8274,186504.0,NaN,...,False,False,False,False,False,False,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6578,GGAL,USD,60min,2023-04-03 12:00:00,9.5499,9.6357,9.5499,9.5756,29258.0,35.345039,...,False,False,False,False,True,False,,,,neutro
6579,GGAL,USD,60min,2023-04-03 13:00:00,9.5671,9.6872,9.5671,9.6700,48527.0,43.814248,...,False,False,False,False,True,False,,,,neutro
6580,GGAL,USD,60min,2023-04-03 14:00:00,9.6785,9.7447,9.6529,9.7301,32877.0,53.958531,...,False,False,False,False,True,False,,,,neutro
6581,GGAL,USD,60min,2023-04-03 15:00:00,9.7386,9.7816,9.6529,9.7558,143309.0,64.423364,...,False,False,False,False,True,False,,,,neutro
6582,GGAL,USD,60min,2023-04-03 16:00:00,9.7472,9.7472,9.7472,9.7472,13155.0,69.770972,...,False,False,False,False,True,False,,,,neutro