Back Testing

In [198]:
from datetime import date, datetime
import pandas as pd
import yfinance as yf
import time
from Alert import Alert
pd.options.mode.chained_assignment = None  # default='warn'
alert = Alert('1h','GGAL')

In [ ]:
input:
    
     Titulo  : example: GGAL
     frequencia de tick : 1h (frequencia mais alta)
     dftitulo : vista do BD sqtitulosalpha.bd (testar ultimos periodas)
Parametros a variar para back testing ( definir rangos de variação)
     k, d, smooth (parametros do stch)
     dayM  (frequencia media) (multiplicador da frequencia mais alta) exemplo: 5
     semM  (frequencia baixa) (multiplicador da frequencia media) exemplo: 7

In [95]:
import sqlite3
import pandas as pd

# Caminho para o banco de dados
caminho_bd = r'C:\Users\scitr\anaconda_projects\Trading_System\Dados_Fontes\Alpha_Vantage\sqtitulosalpha.db'

# Conectando ao banco
conexao = sqlite3.connect(caminho_bd)

# Lendo a view
consulta = 'SELECT * FROM vwtitulosdados ORDER BY datetime'
dftitulosdados = pd.read_sql_query(consulta, conexao)

# Fechando a conexão
conexao.close()

# Exibindo os primeiros registros para conferir
display(dftitulosdados)

,symbol,moeda,intervalo,datetime,open,high,low,close,volume
0,GGAL,USD,60min,2002-12-11 12:00:00,1.3463,1.3463,1.3463,1.3463,1000.0
1,GGAL,USD,60min,2002-12-11 13:00:00,1.3463,1.3463,1.2694,1.3463,4000.0
2,GGAL,USD,60min,2002-12-11 15:00:00,1.3079,1.3463,1.2848,1.3463,2200.0
3,GGAL,USD,60min,2002-12-12 09:00:00,1.3463,1.3694,1.3079,1.3309,25900.0
4,GGAL,USD,60min,2002-12-12 10:00:00,1.3156,1.3156,1.3156,1.3156,1000.0
...,...,...,...,...,...,...,...,...,...
46266,GGAL,USD,60min,2025-05-30 13:00:00,57.0448,57.6221,56.9951,57.4828,84395.0
46267,GGAL,USD,60min,2025-05-30 14:00:00,57.5525,57.6719,57.2041,57.4380,66350.0
46268,GGAL,USD,60min,2025-05-30 15:00:00,57.3633,57.8660,57.1246,57.7416,271800.0
46269,GGAL,USD,60min,2025-05-30 16:00:00,57.7416,57.7814,57.7416,57.7814,1265054.0
46270,GGAL,USD,60min,2025-05-30 19:00:00,57.6321,57.6321,57.6321,57.6321,25.0

In [67]:

i = '1h'
K = 17   
D = 5    
smoth = 8   
dayM = 5   
semM = 4


print (i)

1h

In [69]:
# Stochastic calculation
def stochastic(df, i, K, D, smoth):
        
    df["k"] = (100. * (df.close - df.low.rolling(K).min()) /
        (df.high.rolling(K).max() - df.low.rolling(K).min()))
    
    df["k" + i] = df.k.rolling(smoth).mean()
    df["d" + i] = df["k" + i].rolling(D).mean()
    
    df.drop(columns=["k"], inplace=True)  

    return df
dfstoch = stochastic(dftitulosdados, i, K, D, smoth)
display (dfstoch)

,symbol,moeda,intervalo,datetime,open,high,low,close,volume,k60min,...,time,timeArg,khora,dhora,kdia,ddia,ksem,dsem,k1h,d1h
0,GGAL,USD,60min,2009-02-27 16:00:00,1.4993,1.4993,1.4838,1.4993,6700.0,NaN,...,1970-01-01 00:00:00.000000000,1969-12-31 21:00:00-03:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,GGAL,USD,60min,2009-02-27 15:00:00,1.3370,1.3602,1.2674,1.3292,49206.0,NaN,...,1970-01-01 00:00:00.000000001,1969-12-31 21:00:00.000000001-03:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,GGAL,USD,60min,2009-02-27 14:00:00,1.3756,1.3833,1.3370,1.3524,44994.0,NaN,...,1970-01-01 00:00:00.000000002,1969-12-31 21:00:00.000000002-03:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,GGAL,USD,60min,2009-02-27 13:00:00,1.3524,1.3756,1.3370,1.3679,55020.0,NaN,...,1970-01-01 00:00:00.000000003,1969-12-31 21:00:00.000000003-03:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,GGAL,USD,60min,2009-02-27 12:00:00,1.3602,1.3602,1.3138,1.3524,37724.0,NaN,...,1970-01-01 00:00:00.000000004,1969-12-31 21:00:00.000000004-03:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46266,GGAL,USD,60min,2005-01-03 13:00:00,6.6308,6.6462,6.6153,6.6231,9628.0,89.210627,...,1970-01-01 00:00:00.000046266,1969-12-31 21:00:00.000046266-03:00,89.210627,83.154573,56.584420,54.336330,67.281867,58.393052,89.210627,83.154573
46267,GGAL,USD,60min,2005-01-03 12:00:00,6.6231,6.6462,6.6076,6.6308,8985.0,89.117038,...,1970-01-01 00:00:00.000046267,1969-12-31 21:00:00.000046267-03:00,89.117038,86.249191,57.757773,54.381876,67.574698,58.527864,89.117038,86.249191
46268,GGAL,USD,60min,2005-01-03 11:00:00,6.6462,6.6772,6.6153,6.6153,13601.0,87.955814,...,1970-01-01 00:00:00.000046268,1969-12-31 21:00:00.000046268-03:00,87.955814,87.528415,58.821840,54.448242,67.845528,58.666469,87.955814,87.528415
46269,GGAL,USD,60min,2005-01-03 10:00:00,6.7235,6.7235,6.6540,6.6617,31681.0,89.372740,...,1970-01-01 00:00:00.000046269,1969-12-31 21:00:00.000046269-03:00,89.372740,88.448858,59.909518,54.562028,68.117755,58.808950,89.372740,88.448858
46270,GGAL,USD,60min,2005-01-03 09:00:00,6.5999,6.7235,6.5999,6.7235,6360.0,90.907927,...,1970-01-01 00:00:00.000046270,1969-12-31 21:00:00.000046270-03:00,90.907927,89.312829,61.298357,54.741842,68.400372,58.955422,90.907927,89.312829

In [72]:
def set_test( df, intervalo, k, d, smth, dayM, semM):
        
        # Convert time
        df["time"] = pd.to_datetime(df.index, utc=True)
        df['timeArg'] = df['time'].dt.tz_convert('America/Argentina/Buenos_Aires')
        df['time'] = df['time'].dt.tz_convert(None)

        df = stochastic(df, "hora", k, d, smth)
        df = stochastic(df, "dia", k*dayM, d*dayM, smth*dayM)
        df = stochastic(df, "sem", k*dayM*semM, d*dayM*semM, smth*dayM*semM)
    
        return df
dfstochhlc= set_test(dfstoch, i , K, D, smoth, dayM , semM )
display(dfstochhlc )
%time set_test(dfstoch, i , K, D, smoth, dayM , semM )

,symbol,moeda,intervalo,datetime,open,high,low,close,volume,k60min,...,time,timeArg,khora,dhora,kdia,ddia,ksem,dsem,k1h,d1h
0,GGAL,USD,60min,2009-02-27 16:00:00,1.4993,1.4993,1.4838,1.4993,6700.0,NaN,...,1970-01-01 00:00:00.000000000,1969-12-31 21:00:00-03:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,GGAL,USD,60min,2009-02-27 15:00:00,1.3370,1.3602,1.2674,1.3292,49206.0,NaN,...,1970-01-01 00:00:00.000000001,1969-12-31 21:00:00.000000001-03:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,GGAL,USD,60min,2009-02-27 14:00:00,1.3756,1.3833,1.3370,1.3524,44994.0,NaN,...,1970-01-01 00:00:00.000000002,1969-12-31 21:00:00.000000002-03:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,GGAL,USD,60min,2009-02-27 13:00:00,1.3524,1.3756,1.3370,1.3679,55020.0,NaN,...,1970-01-01 00:00:00.000000003,1969-12-31 21:00:00.000000003-03:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,GGAL,USD,60min,2009-02-27 12:00:00,1.3602,1.3602,1.3138,1.3524,37724.0,NaN,...,1970-01-01 00:00:00.000000004,1969-12-31 21:00:00.000000004-03:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46266,GGAL,USD,60min,2005-01-03 13:00:00,6.6308,6.6462,6.6153,6.6231,9628.0,89.210627,...,1970-01-01 00:00:00.000046266,1969-12-31 21:00:00.000046266-03:00,89.210627,83.154573,56.584420,54.336330,67.281867,58.393052,89.210627,83.154573
46267,GGAL,USD,60min,2005-01-03 12:00:00,6.6231,6.6462,6.6076,6.6308,8985.0,89.117038,...,1970-01-01 00:00:00.000046267,1969-12-31 21:00:00.000046267-03:00,89.117038,86.249191,57.757773,54.381876,67.574698,58.527864,89.117038,86.249191
46268,GGAL,USD,60min,2005-01-03 11:00:00,6.6462,6.6772,6.6153,6.6153,13601.0,87.955814,...,1970-01-01 00:00:00.000046268,1969-12-31 21:00:00.000046268-03:00,87.955814,87.528415,58.821840,54.448242,67.845528,58.666469,87.955814,87.528415
46269,GGAL,USD,60min,2005-01-03 10:00:00,6.7235,6.7235,6.6540,6.6617,31681.0,89.372740,...,1970-01-01 00:00:00.000046269,1969-12-31 21:00:00.000046269-03:00,89.372740,88.448858,59.909518,54.562028,68.117755,58.808950,89.372740,88.448858
46270,GGAL,USD,60min,2005-01-03 09:00:00,6.5999,6.7235,6.5999,6.7235,6360.0,90.907927,...,1970-01-01 00:00:00.000046270,1969-12-31 21:00:00.000046270-03:00,90.907927,89.312829,61.298357,54.741842,68.400372,58.955422,90.907927,89.312829

CPU times: total: 109 ms
Wall time: 112 ms

,symbol,moeda,intervalo,datetime,open,high,low,close,volume,k60min,...,time,timeArg,khora,dhora,kdia,ddia,ksem,dsem,k1h,d1h
0,GGAL,USD,60min,2009-02-27 16:00:00,1.4993,1.4993,1.4838,1.4993,6700.0,NaN,...,1970-01-01 00:00:00.000000000,1969-12-31 21:00:00-03:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,GGAL,USD,60min,2009-02-27 15:00:00,1.3370,1.3602,1.2674,1.3292,49206.0,NaN,...,1970-01-01 00:00:00.000000001,1969-12-31 21:00:00.000000001-03:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,GGAL,USD,60min,2009-02-27 14:00:00,1.3756,1.3833,1.3370,1.3524,44994.0,NaN,...,1970-01-01 00:00:00.000000002,1969-12-31 21:00:00.000000002-03:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,GGAL,USD,60min,2009-02-27 13:00:00,1.3524,1.3756,1.3370,1.3679,55020.0,NaN,...,1970-01-01 00:00:00.000000003,1969-12-31 21:00:00.000000003-03:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,GGAL,USD,60min,2009-02-27 12:00:00,1.3602,1.3602,1.3138,1.3524,37724.0,NaN,...,1970-01-01 00:00:00.000000004,1969-12-31 21:00:00.000000004-03:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46266,GGAL,USD,60min,2005-01-03 13:00:00,6.6308,6.6462,6.6153,6.6231,9628.0,89.210627,...,1970-01-01 00:00:00.000046266,1969-12-31 21:00:00.000046266-03:00,89.210627,83.154573,56.584420,54.336330,67.281867,58.393052,89.210627,83.154573
46267,GGAL,USD,60min,2005-01-03 12:00:00,6.6231,6.6462,6.6076,6.6308,8985.0,89.117038,...,1970-01-01 00:00:00.000046267,1969-12-31 21:00:00.000046267-03:00,89.117038,86.249191,57.757773,54.381876,67.574698,58.527864,89.117038,86.249191
46268,GGAL,USD,60min,2005-01-03 11:00:00,6.6462,6.6772,6.6153,6.6153,13601.0,87.955814,...,1970-01-01 00:00:00.000046268,1969-12-31 21:00:00.000046268-03:00,87.955814,87.528415,58.821840,54.448242,67.845528,58.666469,87.955814,87.528415
46269,GGAL,USD,60min,2005-01-03 10:00:00,6.7235,6.7235,6.6540,6.6617,31681.0,89.372740,...,1970-01-01 00:00:00.000046269,1969-12-31 21:00:00.000046269-03:00,89.372740,88.448858,59.909518,54.562028,68.117755,58.808950,89.372740,88.448858
46270,GGAL,USD,60min,2005-01-03 09:00:00,6.5999,6.7235,6.5999,6.7235,6360.0,90.907927,...,1970-01-01 00:00:00.000046270,1969-12-31 21:00:00.000046270-03:00,90.907927,89.312829,61.298357,54.741842,68.400372,58.955422,90.907927,89.312829

In [79]:
#insere  'COMPRA' no campo oper do df no registro i 
def set_compra( df, i):
        df.loc[i, "oper"] = "COMPRA"
    
#insere  'VENTA' no campo oper do df no registro i 
def set_venta( df, i):
        df.loc[i, "oper"] = "VENTA"


def close_long( df, i, compra, venta):
        df.loc[i, "oper"] = "CLOSELONG"
        if compra !=0.:
            df.loc[i, "long"] = (venta - compra) / compra


def close_short( df, i, compra, venta):
        df.loc[i, "oper"] = "CLOSESHORT"
        if venta !=0.:
            df.loc[i, "short"] = (venta - compra) / venta

In [85]:
def set_signals(df):
        state = ""
        df["compra"] = False
        df["venta"] = False
        df["closeLong"] = False
        df["closeShort"] = False
        df["entradaLongH"] = False
        df["entradaShortH"] = False
        df["oper"] = ""
        df["long"] = ""
        df["short"] = ""
        df["state"] = "neutro"

        compra = 0.
        venta = 0.
#alert.py part 2
        
# outros intervalos
        lastEntradaLongH = False
        lastEntradaShortH = False
            
        for i in df.index:
            l = df.loc[i]
            df.loc[i, "state"] = state

        #for i, l in df.iterrows():
            #df.at[i, "state"] = state
            khora = float(l.khora)
            dhora = float(l.dhora)
            kdia = float(l.kdia)
            ddia = float(l.ddia)
            ksem = float(l.ksem)
            dsem = float(l.dsem)
            
            if (khora > 20) and (khora > dhora):
                    df.at[i, "entradaLongH"] = True
        
                # ESTRATEGIA 1 - Stochastico alineado y esperar cruce
                #if (l.khora > 20. and l.khora > l.dhora):
                    #df.loc[i, "entradaLongH"] = True
                    if (not lastEntradaLongH):
                        if (kdia > 20. and kdia > ddia):
                            if(state == "venta"):
                                df.loc[i, "closeShort"] = True
                                state = "neutro"
                                compra = l.close
                                close_short(df, i, compra, venta)
                            if (ksem > 80. or ksem > dsem):
                                df.loc[i, "compra"] = True
                                if state != "compra":
                                    state = "compra"
                                    compra = l.close
                                    set_compra(df, i)
            else:
                df.loc[i, "entradaLongH"] = False

            if (l.khora < 80. and l.khora < l.dhora):
                    df.loc[i, "entradaShortH"] = True
                    if (not lastEntradaShortH):
                        if(l.kdia < 80. and l.kdia < l.ddia):
                            if(state == "compra"):
                                df.loc[i, "closeLong"] = True
                                state = "neutro"
                                venta = l.close
                                close_long(df, i, compra, venta)
                            if(l.ksem < 20. or l.ksem < l.dsem):
                                df.loc[i, "venta"] = True
                                if state != "venta":
                                    state = "venta"
                                    venta = l.close
                                    set_venta(df, i)
            else:
                    df.loc[i, "entradaShortH"] = False

            lastEntradaLongH = df.loc[i, "entradaLongH"]
            lastEntradaShortH = df.loc[i, "entradaShortH"]
                    
        
        return df
    
dfsignal= set_signals(dfstochhlc)          
display(dfsignal)

,symbol,moeda,intervalo,datetime,open,high,low,close,volume,k60min,...,compra,venta,closeLong,closeShort,entradaLongH,entradaShortH,oper,long,short,state
0,GGAL,USD,60min,2009-02-27 16:00:00,1.4993,1.4993,1.4838,1.4993,6700.0,NaN,...,False,False,False,False,False,False,,,,
1,GGAL,USD,60min,2009-02-27 15:00:00,1.3370,1.3602,1.2674,1.3292,49206.0,NaN,...,False,False,False,False,False,False,,,,
2,GGAL,USD,60min,2009-02-27 14:00:00,1.3756,1.3833,1.3370,1.3524,44994.0,NaN,...,False,False,False,False,False,False,,,,
3,GGAL,USD,60min,2009-02-27 13:00:00,1.3524,1.3756,1.3370,1.3679,55020.0,NaN,...,False,False,False,False,False,False,,,,
4,GGAL,USD,60min,2009-02-27 12:00:00,1.3602,1.3602,1.3138,1.3524,37724.0,NaN,...,False,False,False,False,False,False,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46266,GGAL,USD,60min,2005-01-03 13:00:00,6.6308,6.6462,6.6153,6.6231,9628.0,89.210627,...,False,False,False,False,True,False,,,,neutro
46267,GGAL,USD,60min,2005-01-03 12:00:00,6.6231,6.6462,6.6076,6.6308,8985.0,89.117038,...,False,False,False,False,True,False,,,,neutro
46268,GGAL,USD,60min,2005-01-03 11:00:00,6.6462,6.6772,6.6153,6.6153,13601.0,87.955814,...,False,False,False,False,True,False,,,,neutro
46269,GGAL,USD,60min,2005-01-03 10:00:00,6.7235,6.7235,6.6540,6.6617,31681.0,89.372740,...,False,False,False,False,True,False,,,,neutro
46270,GGAL,USD,60min,2005-01-03 09:00:00,6.5999,6.7235,6.5999,6.7235,6360.0,90.907927,...,False,False,False,False,True,False,,,,neutro

CPU times: total: 1min
Wall time: 1min 1s

,symbol,moeda,intervalo,datetime,open,high,low,close,volume,k60min,...,compra,venta,closeLong,closeShort,entradaLongH,entradaShortH,oper,long,short,state
0,GGAL,USD,60min,2009-02-27 16:00:00,1.4993,1.4993,1.4838,1.4993,6700.0,NaN,...,False,False,False,False,False,False,,,,
1,GGAL,USD,60min,2009-02-27 15:00:00,1.3370,1.3602,1.2674,1.3292,49206.0,NaN,...,False,False,False,False,False,False,,,,
2,GGAL,USD,60min,2009-02-27 14:00:00,1.3756,1.3833,1.3370,1.3524,44994.0,NaN,...,False,False,False,False,False,False,,,,
3,GGAL,USD,60min,2009-02-27 13:00:00,1.3524,1.3756,1.3370,1.3679,55020.0,NaN,...,False,False,False,False,False,False,,,,
4,GGAL,USD,60min,2009-02-27 12:00:00,1.3602,1.3602,1.3138,1.3524,37724.0,NaN,...,False,False,False,False,False,False,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46266,GGAL,USD,60min,2005-01-03 13:00:00,6.6308,6.6462,6.6153,6.6231,9628.0,89.210627,...,False,False,False,False,True,False,,,,neutro
46267,GGAL,USD,60min,2005-01-03 12:00:00,6.6231,6.6462,6.6076,6.6308,8985.0,89.117038,...,False,False,False,False,True,False,,,,neutro
46268,GGAL,USD,60min,2005-01-03 11:00:00,6.6462,6.6772,6.6153,6.6153,13601.0,87.955814,...,False,False,False,False,True,False,,,,neutro
46269,GGAL,USD,60min,2005-01-03 10:00:00,6.7235,6.7235,6.6540,6.6617,31681.0,89.372740,...,False,False,False,False,True,False,,,,neutro
46270,GGAL,USD,60min,2005-01-03 09:00:00,6.5999,6.7235,6.5999,6.7235,6360.0,90.907927,...,False,False,False,False,True,False,,,,neutro

In [87]:
%time set_signals(dfstochhlc)

CPU times: total: 1min 1s
Wall time: 1min 1s

,symbol,moeda,intervalo,datetime,open,high,low,close,volume,k60min,...,compra,venta,closeLong,closeShort,entradaLongH,entradaShortH,oper,long,short,state
0,GGAL,USD,60min,2009-02-27 16:00:00,1.4993,1.4993,1.4838,1.4993,6700.0,NaN,...,False,False,False,False,False,False,,,,
1,GGAL,USD,60min,2009-02-27 15:00:00,1.3370,1.3602,1.2674,1.3292,49206.0,NaN,...,False,False,False,False,False,False,,,,
2,GGAL,USD,60min,2009-02-27 14:00:00,1.3756,1.3833,1.3370,1.3524,44994.0,NaN,...,False,False,False,False,False,False,,,,
3,GGAL,USD,60min,2009-02-27 13:00:00,1.3524,1.3756,1.3370,1.3679,55020.0,NaN,...,False,False,False,False,False,False,,,,
4,GGAL,USD,60min,2009-02-27 12:00:00,1.3602,1.3602,1.3138,1.3524,37724.0,NaN,...,False,False,False,False,False,False,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46266,GGAL,USD,60min,2005-01-03 13:00:00,6.6308,6.6462,6.6153,6.6231,9628.0,89.210627,...,False,False,False,False,True,False,,,,neutro
46267,GGAL,USD,60min,2005-01-03 12:00:00,6.6231,6.6462,6.6076,6.6308,8985.0,89.117038,...,False,False,False,False,True,False,,,,neutro
46268,GGAL,USD,60min,2005-01-03 11:00:00,6.6462,6.6772,6.6153,6.6153,13601.0,87.955814,...,False,False,False,False,True,False,,,,neutro
46269,GGAL,USD,60min,2005-01-03 10:00:00,6.7235,6.7235,6.6540,6.6617,31681.0,89.372740,...,False,False,False,False,True,False,,,,neutro
46270,GGAL,USD,60min,2005-01-03 09:00:00,6.5999,6.7235,6.5999,6.7235,6360.0,90.907927,...,False,False,False,False,True,False,,,,neutro