System construction and test

In [2]:
from datetime import date, datetime
import pandas as pd
import time
import numpy as np
pd.options.mode.chained_assignment = None  # default='warn'
from itertools import product
import sqlite3
from Stoch_HighMedLow_Long import *
from stoploss import *
from index import *
from metrics import *
from backtest import *
from concurrent.futures import ThreadPoolExecutor
import traceback

In [3]:
#seleçonar backtest :  1	1	2020-04-03 19:30:00	2024-04-03 19:30:00	GGAL	60min	USD	C:\Users\scitr\anaconda_projects\Trading_System\Dados_Fontes\Alpha_Vantage\sqtitulosalpha.db
# no DB sqTradeSys
id_backtest = 1

In [4]:
srbacktest = backtest_parameters (id_backtest)
display (srbacktest)

id_backtest                                                    1
id_titulos                                                     1
dataini                                      2020-04-03 19:30:00
datafim                                      2024-04-03 19:30:00
symbol                                                      GGAL
intervalo                                                  60min
moeda                                                        USD
source         C:\Users\scitr\anaconda_projects\Trading_Syste...
Name: 0, dtype: object

In [5]:

dftitulosdados = titulos_dados (srbacktest)
display(len(dftitulosdados))
display(dftitulosdados.head(10))

8957

              datetime    open    high     low   close    volume
0  2020-04-06 08:00:00  5.8034  5.8034  5.8034  5.8034     100.0
1  2020-04-06 09:00:00  6.0432  6.2510  5.9952  6.0832  114582.0
2  2020-04-06 10:00:00  6.0945  6.0945  5.6635  5.7954  159266.0
3  2020-04-06 11:00:00  5.7954  5.8034  5.4837  5.6835  242263.0
4  2020-04-06 12:00:00  5.6715  5.8354  5.6355  5.8274  186504.0
5  2020-04-06 13:00:00  5.8274  5.8354  5.7474  5.7834   68220.0
6  2020-04-06 14:00:00  5.7714  5.7794  5.6435  5.6435   84043.0
7  2020-04-06 15:00:00  5.6595  5.6595  5.5316  5.5956  122920.0
8  2020-04-06 16:00:00  5.6036  5.6036  5.6036  5.6036   49293.0
9  2020-04-07 09:00:00  5.9793  6.0672  5.7395  6.0032  101621.0

In [9]:

dfcomb = scripts_parameters(id_backtest)
display (dfcomb)

        name   type    max    min   step
0          K    int     30     20      2
1          D    int     15     15      1
2      smoth    int     12     11      1
3       medM    int      6      6      1
4       lowM    int      5      5      1
5       stpl  float   0.02   0.02   0.01
6  comission  float  0.003  0.003  0.001
7    drawmax  float    0.2   0.02    0.1

In [19]:
                      



dfparamtest = parameters_combinator(dfcomb)
print(dfparamtest)

     K   D  smoth  medM  lowM  stpl  comission  drawmax
0   20  15     11     6     5  0.02      0.003     0.02
1   20  15     11     6     5  0.02      0.003     0.12
2   20  15     11     6     5  0.02      0.003     0.22
3   20  15     12     6     5  0.02      0.003     0.02
4   20  15     12     6     5  0.02      0.003     0.12
5   20  15     12     6     5  0.02      0.003     0.22
6   22  15     11     6     5  0.02      0.003     0.02
7   22  15     11     6     5  0.02      0.003     0.12
8   22  15     11     6     5  0.02      0.003     0.22
9   22  15     12     6     5  0.02      0.003     0.02
10  22  15     12     6     5  0.02      0.003     0.12
11  22  15     12     6     5  0.02      0.003     0.22
12  24  15     11     6     5  0.02      0.003     0.02
13  24  15     11     6     5  0.02      0.003     0.12
14  24  15     11     6     5  0.02      0.003     0.22
15  24  15     12     6     5  0.02      0.003     0.02
16  24  15     12     6     5  0.02      0.003     0.12
17  24  15     12     6     5  0.02      0.003     0.22
18  26  15     11     6     5  0.02      0.003     0.02
19  26  15     11     6     5  0.02      0.003     0.12
20  26  15     11     6     5  0.02      0.003     0.22
21  26  15     12     6     5  0.02      0.003     0.02
22  26  15     12     6     5  0.02      0.003     0.12
23  26  15     12     6     5  0.02      0.003     0.22
24  28  15     11     6     5  0.02      0.003     0.02
25  28  15     11     6     5  0.02      0.003     0.12
26  28  15     11     6     5  0.02      0.003     0.22
27  28  15     12     6     5  0.02      0.003     0.02
28  28  15     12     6     5  0.02      0.003     0.12
29  28  15     12     6     5  0.02      0.003     0.22
30  30  15     11     6     5  0.02      0.003     0.02
31  30  15     11     6     5  0.02      0.003     0.12
32  30  15     11     6     5  0.02      0.003     0.22
33  30  15     12     6     5  0.02      0.003     0.02
34  30  15     12     6     5  0.02      0.003     0.12
35  30  15     12     6     5  0.02      0.003     0.22

In [21]:
print(len(dfparamtest)*len(dftitulosdados))

322452

START LOOP

In [26]:

dfmetricas = processar_parametros_simple (dfparamtest, dftitulosdados, srbacktest)      
display (dfmetricas)

,K,D,smoth,medM,lowM,stpl,comission,drawmax,tirtotalanual,tiranualquant,...,diasoutmedia,diasoutmax,diasoutmin,diasoutstd,stopsysfirst,stopsysquant,stopsysmedia,stopsysmaximo,stopsysminimo,stopsystd
0,20.0,15.0,11.0,6.0,5.0,0.02,0.003,0.02,0.039553,3.0,...,38.04,120.0,2.0,36.74,97.679857,20.0,103.075355,119.326036,87.379861,7.929295
1,20.0,15.0,11.0,6.0,5.0,0.02,0.003,0.12,0.039553,3.0,...,38.04,120.0,2.0,36.74,87.379861,3.0,96.135883,107.115319,87.379861,10.053843
2,20.0,15.0,11.0,6.0,5.0,0.02,0.003,0.22,0.039553,3.0,...,38.04,120.0,2.0,36.74,93.912471,1.0,93.912471,93.912471,93.912471,NaN
3,20.0,15.0,12.0,6.0,5.0,0.02,0.003,0.02,-0.081638,3.0,...,36.52,146.0,1.0,39.53,97.495797,27.0,88.991345,105.879261,71.114998,10.287505
4,20.0,15.0,12.0,6.0,5.0,0.02,0.003,0.12,-0.081638,3.0,...,36.52,146.0,1.0,39.53,94.235504,4.0,85.828708,94.235504,78.193854,8.355830
5,20.0,15.0,12.0,6.0,5.0,0.02,0.003,0.22,-0.081638,3.0,...,36.52,146.0,1.0,39.53,84.247942,1.0,84.247942,84.247942,84.247942,NaN
6,22.0,15.0,11.0,6.0,5.0,0.02,0.003,0.02,0.090441,3.0,...,44.82,145.0,1.0,42.64,97.360957,17.0,108.711620,126.487475,89.058712,9.154571
7,22.0,15.0,11.0,6.0,5.0,0.02,0.003,0.12,0.090441,3.0,...,44.82,145.0,1.0,42.64,105.623166,1.0,105.623166,105.623166,105.623166,NaN
8,22.0,15.0,11.0,6.0,5.0,0.02,0.003,0.22,0.090441,3.0,...,44.82,145.0,1.0,42.64,0.000000,0.0,0.000000,0.000000,0.000000,0.000000
9,22.0,15.0,12.0,6.0,5.0,0.02,0.003,0.02,-0.110372,3.0,...,40.88,141.0,1.0,39.53,97.675415,27.0,85.336299,106.216865,64.117965,12.143791
10,22.0,15.0,12.0,6.0,5.0,0.02,0.003,0.12,-0.110372,3.0,...,40.88,141.0,1.0,39.53,87.375887,5.0,81.843862,93.724634,70.500330,9.903398
11,22.0,15.0,12.0,6.0,5.0,0.02,0.003,0.22,-0.110372,3.0,...,40.88,141.0,1.0,39.53,84.869731,2.0,74.493848,84.869731,64.117965,14.673715
12,24.0,15.0,11.0,6.0,5.0,0.02,0.003,0.02,0.132372,3.0,...,42.05,120.0,1.0,37.69,117.850571,15.0,129.461840,146.699204,116.226601,9.080919
13,24.0,15.0,11.0,6.0,5.0,0.02,0.003,0.12,0.132372,3.0,...,42.05,120.0,1.0,37.69,119.256131,1.0,119.256131,119.256131,119.256131,NaN
14,24.0,15.0,11.0,6.0,5.0,0.02,0.003,0.22,0.132372,3.0,...,42.05,120.0,1.0,37.69,0.000000,0.0,0.000000,0.000000,0.000000,0.000000
15,24.0,15.0,12.0,6.0,5.0,0.02,0.003,0.02,-0.069301,3.0,...,39.08,120.0,1.0,34.13,95.906206,26.0,93.097264,107.099490,75.837136,7.855809
16,24.0,15.0,12.0,6.0,5.0,0.02,0.003,0.12,-0.069301,3.0,...,39.08,120.0,1.0,34.13,93.166414,3.0,89.256514,93.166414,83.386039,5.176565
17,24.0,15.0,12.0,6.0,5.0,0.02,0.003,0.22,-0.069301,3.0,...,39.08,120.0,1.0,34.13,84.526979,1.0,84.526979,84.526979,84.526979,NaN
18,26.0,15.0,11.0,6.0,5.0,0.02,0.003,0.02,-0.005688,3.0,...,42.09,120.0,4.0,35.77,97.685670,23.0,106.347952,120.541556,94.100232,8.870792
19,26.0,15.0,11.0,6.0,5.0,0.02,0.003,0.12,-0.005688,3.0,...,42.09,120.0,4.0,35.77,107.958014,3.0,103.407294,108.163635,94.100232,8.060807
20,26.0,15.0,11.0,6.0,5.0,0.02,0.003,0.22,-0.005688,3.0,...,42.09,120.0,4.0,35.77,94.100232,1.0,94.100232,94.100232,94.100232,NaN
21,26.0,15.0,12.0,6.0,5.0,0.02,0.003,0.02,-0.119022,3.0,...,38.04,121.0,1.0,35.43,98.138400,30.0,88.110241,107.503465,64.612311,10.846136
22,26.0,15.0,12.0,6.0,5.0,0.02,0.003,0.12,-0.119022,3.0,...,38.04,121.0,1.0,35.43,88.690450,5.0,81.619750,95.959678,64.612311,12.253746
23,26.0,15.0,12.0,6.0,5.0,0.02,0.003,0.22,-0.119022,3.0,...,38.04,121.0,1.0,35.43,84.216166,2.0,74.414238,84.216166,64.612311,13.862018
24,28.0,15.0,11.0,6.0,5.0,0.02,0.003,0.02,-0.111428,3.0,...,38.88,120.0,3.0,35.59,97.419066,31.0,90.605526,110.608845,66.509089,10.154932
25,28.0,15.0,11.0,6.0,5.0,0.02,0.003,0.12,-0.111428,3.0,...,38.88,120.0,3.0,35.59,87.518567,5.0,84.004387,96.131040,69.413141,9.935280
26,28.0,15.0,11.0,6.0,5.0,0.02,0.003,0.22,-0.111428,3.0,...,38.88,120.0,3.0,35.59,88.029109,2.0,78.721125,88.029109,69.413141,13.163478
27,28.0,15.0,12.0,6.0,5.0,0.02,0.003,0.02,-0.027346,3.0,...,42.36,120.0,2.0,36.24,98.120411,22.0,86.914847,98.847398,75.992916,7.219483
28,28.0,15.0,12.0,6.0,5.0,0.02,0.003,0.12,-0.027346,3.0,...,42.36,120.0,2.0,36.24,89.447627,3.0,83.820041,89.447627,79.891033,4.999600
29,28.0,15.0,12.0,6.0,5.0,0.02,0.003,0.22,-0.027346,3.0,...,42.36,120.0,2.0,36.24,78.270898,1.0,78.270898,78.270898,78.270898,NaN
30,30.0,15.0,11.0,6.0,5.0,0.02,0.003,0.02,-0.126027,3.0,...,36.80,120.0,1.0,36.98,98.943514,33.0,84.373527,98.943514,60.957739,9.766543
31,30.0,15.0,11.0,6.0,5.0,0.02,0.003,0.12,-0.126027,3.0,...,36.80,120.0,1.0,36.98,84.873071,6.0,77.351011,87.742781,63.519470,8.675020
32,30.0,15.0,11.0,6.0,5.0,0.02,0.003,0.22,-0.126027,3.0,...,36.80,120.0,1.0,36.98,78.386841,3.0,73.138521,78.386841,63.519470,8.341891
33,30.0,15.0,12.0,6.0,5.0,0.02,0.003,0.02,-0.115815,3.0,...,37.28,120.0,1.0,36.87,98.362229,30.0,88.133792,104.787786,66.041142,10.615762
34,30.0,15.0,12.0,6.0,5.0,0.02,0.003,0.12,-0.115815,3.0,...,37.28,120.0,1.0,36.87,88.451468,4.0,82.992102,93.333508,70.190425,10.159181
35,30.0,15.0,12.0,6.0,5.0,0.02,0.003,0.22,-0.115815,3.0,...,37.28,120.0,1.0,36.87,79.993006,1.0,79.993006,79.993006,79.993006,NaN

In [66]:
from concurrent.futures import ThreadPoolExecutor
import traceback

def processar_parametros_multinucleo(dfparamtest, dftitulosdados, srbacktest, dfmetricas):

    dfmetricas = None

    def processar_parametros(args):
        il, linha, dftitulosdados, dataini, datafim = args
        try:
            K, D, smoth, medM, lowM, stpl, comission, drawmax, lsmetricas = parametros(dfparamtest, il)

            dfsignals = Stoch_HighMedLow_Long(dftitulosdados, K, D, smoth, medM, lowM)
            dfsignals, dfstoploss = stop_loss_reentry(dfsignals, stpl)
            dfindex = index_calculation(dfsignals, comission)
            dfindexdrawdown = stop_drawdown_simple(dfindex, drawmax)

            dfinputmetricas = dfindex[['datetime', 'state', 'index_sc', 'index', 'trade']]
            setirtotalanual, lsmetricas = tir_total_anualizada(dfinputmetricas, lsmetricas)
            dftiranual = tir_anuais_df(dfinputmetricas, dataini, datafim)
            setiranuaisestats, lsmetricas = tir_anuais_estats(dftiranual, lsmetricas)
            setradesestats, lsmetricas = trades_estats(dfinputmetricas, lsmetricas)
            dfdrawdowns = drawdowns_df(dfinputmetricas)
            sedrawdownsestats, lsmetricas = drawdowns_estats(dfdrawdowns, lsmetricas)
            dfdiasout = dias_out_df(dfinputmetricas)
            sediasoutestats, lsmetricas = dias_out_estats(dfdiasout, lsmetricas)
            dfstopdrawdown = stop_drawdown_df(dfindexdrawdown)
            sestopdrawdownestats, lsmetricas = stop_drawdown_estats(dfstopdrawdown, lsmetricas)

            return lsmetricas

        except Exception as e:
            print(f"⚠️ Erro ao processar índice {il}: {e}")
            traceback.print_exc()
            return None

    # Prepara os argumentos para cada linha
    args_list = [
        (il, dfparamtest.iloc[il], dftitulosdados, srbacktest['dataini'], srbacktest['datafim'])
        for il in dfparamtest.index
    ]

    # Executa em paralelo
    resultados = []
    with ThreadPoolExecutor() as executor:
        for resultado in executor.map(processar_parametros, args_list):
            if resultado is not None:
                resultados.append(resultado)

    # Atualiza dfmetricas com os resultados válidos
    for lsmetricas in resultados:
        dfmetricas = atualizar_df_metricas(dfmetricas, lsmetricas)

    return dfmetricas

In [68]:
dfmetricas = processar_parametros_multinucleo(dfparamtest, dftitulosdados, srbacktest, dfmetricas)

END LOOP

In [70]:
dfmetricas.insert(
    loc=0,  # insere como primeira coluna
    column="id_backtest",
    value=[srbacktest["id_backtest"]] * len(dfmetricas)
)
display(dfmetricas)

,id_backtest,K,D,smoth,medM,lowM,stpl,comission,drawmax,tirtotalanual,...,diasoutmedia,diasoutmax,diasoutmin,diasoutstd,stopsysfirst,stopsysquant,stopsysmedia,stopsysmaximo,stopsysminimo,stopsystd
0,1,20.0,15.0,11.0,6.0,5.0,0.02,0.003,0.02,0.039553,...,38.04,120.0,2.0,36.74,97.679857,20.0,103.075355,119.326036,87.379861,7.929295
1,1,20.0,15.0,11.0,6.0,5.0,0.02,0.003,0.12,0.039553,...,38.04,120.0,2.0,36.74,87.379861,3.0,96.135883,107.115319,87.379861,10.053843
2,1,20.0,15.0,11.0,6.0,5.0,0.02,0.003,0.22,0.039553,...,38.04,120.0,2.0,36.74,93.912471,1.0,93.912471,93.912471,93.912471,NaN
3,1,20.0,15.0,12.0,6.0,5.0,0.02,0.003,0.02,-0.081638,...,36.52,146.0,1.0,39.53,97.495797,27.0,88.991345,105.879261,71.114998,10.287505
4,1,20.0,15.0,12.0,6.0,5.0,0.02,0.003,0.12,-0.081638,...,36.52,146.0,1.0,39.53,94.235504,4.0,85.828708,94.235504,78.193854,8.355830
5,1,20.0,15.0,12.0,6.0,5.0,0.02,0.003,0.22,-0.081638,...,36.52,146.0,1.0,39.53,84.247942,1.0,84.247942,84.247942,84.247942,NaN
6,1,22.0,15.0,11.0,6.0,5.0,0.02,0.003,0.02,0.090441,...,44.82,145.0,1.0,42.64,97.360957,17.0,108.711620,126.487475,89.058712,9.154571
7,1,22.0,15.0,11.0,6.0,5.0,0.02,0.003,0.12,0.090441,...,44.82,145.0,1.0,42.64,105.623166,1.0,105.623166,105.623166,105.623166,NaN
8,1,22.0,15.0,11.0,6.0,5.0,0.02,0.003,0.22,0.090441,...,44.82,145.0,1.0,42.64,0.000000,0.0,0.000000,0.000000,0.000000,0.000000
9,1,22.0,15.0,12.0,6.0,5.0,0.02,0.003,0.02,-0.110372,...,40.88,141.0,1.0,39.53,97.675415,27.0,85.336299,106.216865,64.117965,12.143791
10,1,22.0,15.0,12.0,6.0,5.0,0.02,0.003,0.12,-0.110372,...,40.88,141.0,1.0,39.53,87.375887,5.0,81.843862,93.724634,70.500330,9.903398
11,1,22.0,15.0,12.0,6.0,5.0,0.02,0.003,0.22,-0.110372,...,40.88,141.0,1.0,39.53,84.869731,2.0,74.493848,84.869731,64.117965,14.673715
12,1,24.0,15.0,11.0,6.0,5.0,0.02,0.003,0.02,0.132372,...,42.05,120.0,1.0,37.69,117.850571,15.0,129.461840,146.699204,116.226601,9.080919
13,1,24.0,15.0,11.0,6.0,5.0,0.02,0.003,0.12,0.132372,...,42.05,120.0,1.0,37.69,119.256131,1.0,119.256131,119.256131,119.256131,NaN
14,1,24.0,15.0,11.0,6.0,5.0,0.02,0.003,0.22,0.132372,...,42.05,120.0,1.0,37.69,0.000000,0.0,0.000000,0.000000,0.000000,0.000000
15,1,24.0,15.0,12.0,6.0,5.0,0.02,0.003,0.02,-0.069301,...,39.08,120.0,1.0,34.13,95.906206,26.0,93.097264,107.099490,75.837136,7.855809
16,1,24.0,15.0,12.0,6.0,5.0,0.02,0.003,0.12,-0.069301,...,39.08,120.0,1.0,34.13,93.166414,3.0,89.256514,93.166414,83.386039,5.176565
17,1,24.0,15.0,12.0,6.0,5.0,0.02,0.003,0.22,-0.069301,...,39.08,120.0,1.0,34.13,84.526979,1.0,84.526979,84.526979,84.526979,NaN
18,1,26.0,15.0,11.0,6.0,5.0,0.02,0.003,0.02,-0.005688,...,42.09,120.0,4.0,35.77,97.685670,23.0,106.347952,120.541556,94.100232,8.870792
19,1,26.0,15.0,11.0,6.0,5.0,0.02,0.003,0.12,-0.005688,...,42.09,120.0,4.0,35.77,107.958014,3.0,103.407294,108.163635,94.100232,8.060807
20,1,26.0,15.0,11.0,6.0,5.0,0.02,0.003,0.22,-0.005688,...,42.09,120.0,4.0,35.77,94.100232,1.0,94.100232,94.100232,94.100232,NaN
21,1,26.0,15.0,12.0,6.0,5.0,0.02,0.003,0.02,-0.119022,...,38.04,121.0,1.0,35.43,98.138400,30.0,88.110241,107.503465,64.612311,10.846136
22,1,26.0,15.0,12.0,6.0,5.0,0.02,0.003,0.12,-0.119022,...,38.04,121.0,1.0,35.43,88.690450,5.0,81.619750,95.959678,64.612311,12.253746
23,1,26.0,15.0,12.0,6.0,5.0,0.02,0.003,0.22,-0.119022,...,38.04,121.0,1.0,35.43,84.216166,2.0,74.414238,84.216166,64.612311,13.862018
24,1,28.0,15.0,11.0,6.0,5.0,0.02,0.003,0.02,-0.111428,...,38.88,120.0,3.0,35.59,97.419066,31.0,90.605526,110.608845,66.509089,10.154932
25,1,28.0,15.0,11.0,6.0,5.0,0.02,0.003,0.12,-0.111428,...,38.88,120.0,3.0,35.59,87.518567,5.0,84.004387,96.131040,69.413141,9.935280
26,1,28.0,15.0,11.0,6.0,5.0,0.02,0.003,0.22,-0.111428,...,38.88,120.0,3.0,35.59,88.029109,2.0,78.721125,88.029109,69.413141,13.163478
27,1,28.0,15.0,12.0,6.0,5.0,0.02,0.003,0.02,-0.027346,...,42.36,120.0,2.0,36.24,98.120411,22.0,86.914847,98.847398,75.992916,7.219483
28,1,28.0,15.0,12.0,6.0,5.0,0.02,0.003,0.12,-0.027346,...,42.36,120.0,2.0,36.24,89.447627,3.0,83.820041,89.447627,79.891033,4.999600
29,1,28.0,15.0,12.0,6.0,5.0,0.02,0.003,0.22,-0.027346,...,42.36,120.0,2.0,36.24,78.270898,1.0,78.270898,78.270898,78.270898,NaN
30,1,30.0,15.0,11.0,6.0,5.0,0.02,0.003,0.02,-0.126027,...,36.80,120.0,1.0,36.98,98.943514,33.0,84.373527,98.943514,60.957739,9.766543
31,1,30.0,15.0,11.0,6.0,5.0,0.02,0.003,0.12,-0.126027,...,36.80,120.0,1.0,36.98,84.873071,6.0,77.351011,87.742781,63.519470,8.675020
32,1,30.0,15.0,11.0,6.0,5.0,0.02,0.003,0.22,-0.126027,...,36.80,120.0,1.0,36.98,78.386841,3.0,73.138521,78.386841,63.519470,8.341891
33,1,30.0,15.0,12.0,6.0,5.0,0.02,0.003,0.02,-0.115815,...,37.28,120.0,1.0,36.87,98.362229,30.0,88.133792,104.787786,66.041142,10.615762
34,1,30.0,15.0,12.0,6.0,5.0,0.02,0.003,0.12,-0.115815,...,37.28,120.0,1.0,36.87,88.451468,4.0,82.992102,93.333508,70.190425,10.159181
35,1,30.0,15.0,12.0,6.0,5.0,0.02,0.003,0.22,-0.115815,...,37.28,120.0,1.0,36.87,79.993006,1.0,79.993006,79.993006,79.993006,NaN