System construction and test

In [2]:
from datetime import date, datetime
import pandas as pd
import yfinance as yf
import time
import numpy as np
#from Alert import Alert
pd.options.mode.chained_assignment = None  # default='warn'
#alert = Alert('1h','GGAL')

input:
    
     Titulo  : example: GGAL
     frequencia de tick : 1h (frequencia mais alta)
     dftitulo : vista do BD sqtitulosalpha.bd (testar ultimos periodas)
Parametros a variar para back testing ( definir rangos de variação)
     k, d, smooth (parametros do stch)
     dayM  (frequencia media) (multiplicador da frequencia mais alta) exemplo: 5
     semM  (frequencia baixa) (multiplicador da frequencia media) exemplo: 7

In [5]:
dataini = '2004-04-03 19:30:00'
datafim = '2024-04-03 19:30:00'

In [7]:
#%%timeit
import sqlite3
import pandas as pd

# Caminho para o banco de dados
caminho_bd = r'C:\Users\scitr\anaconda_projects\Trading_System\Dados_Fontes\Alpha_Vantage\sqtitulosalpha.db'

# Conectando ao banco
conexao = sqlite3.connect(caminho_bd)

# Lendo a view
#consulta = 'SELECT * FROM vwtitulosdados ORDER BY datetime'
consulta = f"""
SELECT * FROM vwtitulosdados
WHERE datetime BETWEEN '{dataini}' AND '{datafim}'
ORDER BY datetime
"""

dftitulosdados = pd.read_sql_query(consulta, conexao)

# Fechando a conexão
conexao.close()

# Exibindo os primeiros registros para conferir
#display(dftitulosdados)
dftitulosdados = dftitulosdados.drop(columns=["symbol", "moeda", "intervalo","volume"])
display(len(dftitulosdados))
#display(dftitulosdados.head(10))

40717

In [9]:

i = 'high'
K = 16  
D = 5    
smoth = 5  
medM = 8  
lowM = 10
stpl = 0.02
comission = 0.0035
taxalivrerisgoprom = 0.05
drawmax = -0.1

In [11]:
#%%timeit
# Stochastic calculation
def stochastic(dftitulosdados, i, K, D, smoth):
    df = dftitulosdados    
    df["k"] = (100. * (df.close - df.low.rolling(K).min()) /
        (df.high.rolling(K).max() - df.low.rolling(K).min()))
    
    df["k" + i ] = df.k.rolling(smoth).mean()
    df["d" + i ] = df["k" + i].rolling(D).mean()
    
    df.drop(columns=["k"], inplace=True)  
    dfstoch = df
    return dfstoch

In [13]:
dfstoch = stochastic(dftitulosdados, i, K, D, smoth)
display (dfstoch.head(10))

              datetime    open    high     low   close  khigh  dhigh
0  2004-04-05 09:00:00  6.6778  6.6778  6.4162  6.4162    NaN    NaN
1  2004-04-05 10:00:00  6.6547  6.6770  6.5085  6.5085    NaN    NaN
2  2004-04-05 11:00:00  6.5539  6.5547  6.4393  6.5470    NaN    NaN
3  2004-04-05 12:00:00  6.5470  6.6162  6.5470  6.6085    NaN    NaN
4  2004-04-05 13:00:00  6.5701  6.5701  6.5470  6.5470    NaN    NaN
5  2004-04-05 14:00:00  6.5547  6.5547  6.5470  6.5470    NaN    NaN
6  2004-04-05 15:00:00  6.5470  6.6162  6.5470  6.5470    NaN    NaN
7  2004-04-06 09:00:00  6.5008  6.5239  6.3931  6.4778    NaN    NaN
8  2004-04-06 10:00:00  6.4162  6.4624  6.3393  6.3854    NaN    NaN
9  2004-04-06 11:00:00  6.3854  6.3854  6.2546  6.3008    NaN    NaN

In [15]:
#%%timeit
# stochastic high, med and low frcuency

def stoch_hml( dfstoch, k, d, smth, medM, lowM): 
    df = dfstoch
    df = stochastic(df, "high", k, d, smth)
    df = stochastic(df, "med", k*medM, d*medM, smth*medM)
    df = stochastic(df, "low", k*medM*lowM, d*medM*lowM, smth*medM*lowM)
    dfstoch_hml = df
    return dfstoch_hml

In [17]:
dfstoch_hml= stoch_hml(dfstoch , K, D, smoth, medM , lowM )
display(dfstoch_hml.head(10) )

,datetime,open,high,low,close,khigh,dhigh,kmed,dmed,klow,dlow
0,2004-04-05 09:00:00,6.6778,6.6778,6.4162,6.4162,NaN,NaN,NaN,NaN,NaN,NaN
1,2004-04-05 10:00:00,6.6547,6.6770,6.5085,6.5085,NaN,NaN,NaN,NaN,NaN,NaN
2,2004-04-05 11:00:00,6.5539,6.5547,6.4393,6.5470,NaN,NaN,NaN,NaN,NaN,NaN
3,2004-04-05 12:00:00,6.5470,6.6162,6.5470,6.6085,NaN,NaN,NaN,NaN,NaN,NaN
4,2004-04-05 13:00:00,6.5701,6.5701,6.5470,6.5470,NaN,NaN,NaN,NaN,NaN,NaN
5,2004-04-05 14:00:00,6.5547,6.5547,6.5470,6.5470,NaN,NaN,NaN,NaN,NaN,NaN
6,2004-04-05 15:00:00,6.5470,6.6162,6.5470,6.5470,NaN,NaN,NaN,NaN,NaN,NaN
7,2004-04-06 09:00:00,6.5008,6.5239,6.3931,6.4778,NaN,NaN,NaN,NaN,NaN,NaN
8,2004-04-06 10:00:00,6.4162,6.4624,6.3393,6.3854,NaN,NaN,NaN,NaN,NaN,NaN
9,2004-04-06 11:00:00,6.3854,6.3854,6.2546,6.3008,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
#%%timeit
def system_criterias (dfstoch_hml):   # input  df() =  dfstoch_hml ()
    df = dfstoch_hml
    df["longbuylow"] = ((df["klow"] > 20) & (df["klow"] > df["dlow"])).astype(int)
    df["longbuymed"] = ((df["kmed"] > 20) & (df["kmed"] > df["dmed"])).astype(int)
    df["longbuyhigh"] = ((df["khigh"] > 20) & (df["khigh"] > df["dhigh"])).astype(int)
    dfcriterias = df
    return dfcriterias

In [21]:
dfcriterias = system_criterias (dfstoch_hml)
display (dfcriterias.head(10))

,datetime,open,high,low,close,khigh,dhigh,kmed,dmed,klow,dlow,longbuylow,longbuymed,longbuyhigh
0,2004-04-05 09:00:00,6.6778,6.6778,6.4162,6.4162,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0
1,2004-04-05 10:00:00,6.6547,6.6770,6.5085,6.5085,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0
2,2004-04-05 11:00:00,6.5539,6.5547,6.4393,6.5470,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0
3,2004-04-05 12:00:00,6.5470,6.6162,6.5470,6.6085,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0
4,2004-04-05 13:00:00,6.5701,6.5701,6.5470,6.5470,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0
5,2004-04-05 14:00:00,6.5547,6.5547,6.5470,6.5470,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0
6,2004-04-05 15:00:00,6.5470,6.6162,6.5470,6.5470,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0
7,2004-04-06 09:00:00,6.5008,6.5239,6.3931,6.4778,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0
8,2004-04-06 10:00:00,6.4162,6.4624,6.3393,6.3854,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0
9,2004-04-06 11:00:00,6.3854,6.3854,6.2546,6.3008,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0

dfsignals = system_signals(dfcriterias)
display (dfsignals.head(10))

In [23]:
##%%timeit
def system_signals (dfcriterias):
    df = dfcriterias
    n = len(df)
    state_array = np.full(n, "standby", dtype=object)  # inicializa com "standby"
    estado_anterior = "standby"

    high = df["longbuyhigh"].to_numpy()
    med = df["longbuymed"].to_numpy()
    low = df["longbuylow"].to_numpy()

    for i in range(1, n):
        if high[i] == 1 and med[i] == 1 and low[i] == 1 and estado_anterior == "standby":
            state_array[i] = "enter"
            estado_anterior = "enter"
        elif med[i] == 1 and low[i] == 1 and estado_anterior in ["enter", "stay"]:
            state_array[i] = "stay"
            estado_anterior = "stay"
        elif high[i] == 1 and low[i] == 1 and med[i] == 0 and estado_anterior in ["enter", "stay"]:
            state_array[i] = "stay"
            estado_anterior = "stay"
        elif low[i] == 0 and estado_anterior in ["enter", "stay"]:
            state_array[i] = "out"
            estado_anterior = "out"
        elif high[i] == 0 and med[i] == 0 and estado_anterior in ["enter", "stay"]:
            state_array[i] = "out"
            estado_anterior = "out"
        elif (low[i] == 0 or med[i] == 0) and estado_anterior == "out":
            state_array[i] = "standby"
            estado_anterior = "standby"
        else:
            state_array[i] = estado_anterior

    df["state"] = state_array
    dfsignals = df
    return df

In [25]:
dfsignals = system_signals (dfcriterias)
display (dfsignals.head(10))

,datetime,open,high,low,close,khigh,dhigh,kmed,dmed,klow,dlow,longbuylow,longbuymed,longbuyhigh,state
0,2004-04-05 09:00:00,6.6778,6.6778,6.4162,6.4162,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,standby
1,2004-04-05 10:00:00,6.6547,6.6770,6.5085,6.5085,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,standby
2,2004-04-05 11:00:00,6.5539,6.5547,6.4393,6.5470,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,standby
3,2004-04-05 12:00:00,6.5470,6.6162,6.5470,6.6085,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,standby
4,2004-04-05 13:00:00,6.5701,6.5701,6.5470,6.5470,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,standby
5,2004-04-05 14:00:00,6.5547,6.5547,6.5470,6.5470,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,standby
6,2004-04-05 15:00:00,6.5470,6.6162,6.5470,6.5470,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,standby
7,2004-04-06 09:00:00,6.5008,6.5239,6.3931,6.4778,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,standby
8,2004-04-06 10:00:00,6.4162,6.4624,6.3393,6.3854,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,standby
9,2004-04-06 11:00:00,6.3854,6.3854,6.2546,6.3008,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,standby

Stop Loss Reentry

In [28]:
#%%timeit
def stop_loss_reentry (dfsignals, stpl) :

    df = dfsignals[(dfsignals['state'] == 'enter') | (dfsignals['state'] == 'stay')]
    df = df.reset_index(drop=True)
    df = df.drop(columns=["open" ,	"high" , "low" , "khigh","dhigh","kmed" ,"dmed","klow","dlow"])
    #drop(columns=["symbol", "moeda", "intervalo","volume"])
    df["stpl"] = 0.0
    stoplossprice = 0.0
    lastlongbuyprice = 0.0

    for i in range(0, len(df)):
        
        if df.loc[i, "state"] == "enter" :
           stoplossprice = df.loc[i, "close"]
           df.loc[i,"stpl"] = df.loc[i, "close"] - stoplossprice * (1 - stpl)
           
        if df.loc[i, "state"]== "stay" :
           df.loc[i, "stpl"] = df.loc[i, "close"] - stoplossprice * (1- stpl)
            
           if df.loc[i, "stpl"] < 0.0 :
                df.loc[i, "state"] = "out"
               
           if df.loc[i, "stpl"] > 0.0 and   (df.loc[i-1, "state"] == "out" or df.loc[i-1, "state"] == "outstpl") :
                df.loc[i, "state"] = "enter"
               
           if df.loc[i, "stpl"] < 0.0 and   (df.loc[i-1, "state"] == "out" or df.loc[i-1, "state"] == "outstpl") :
                df.loc[i, "state"] = "outstpl"

    return df

In [30]:
dfstoploss = stop_loss_reentry (dfsignals, stpl)
display(dfstoploss.head(10))

,datetime,close,longbuylow,longbuymed,longbuyhigh,state,stpl
0,2006-04-05 13:00:00,5.9816,1,1,1,enter,0.119632
1,2006-04-05 14:00:00,5.9816,1,1,1,stay,0.119632
2,2006-04-05 15:00:00,5.9507,1,1,1,stay,0.088732
3,2006-04-05 16:00:00,5.9507,1,1,1,stay,0.088732
4,2006-04-06 09:00:00,5.9198,1,1,0,stay,0.057832
5,2006-04-06 10:00:00,5.8966,1,1,0,stay,0.034632
6,2006-04-06 11:00:00,5.8966,1,1,0,stay,0.034632
7,2006-04-06 12:00:00,5.8889,1,1,0,stay,0.026932
8,2006-04-06 13:00:00,5.8889,1,1,0,stay,0.026932
9,2006-04-06 14:00:00,5.9043,1,1,0,stay,0.042332

In [32]:
#%%timeit
# preparar dataframe para calcular index 
def index_dataframe (dfsignals, dfstoploss) :
    # elimino colunas de dfsignals e filtro por os valores "out"
    dfsignalsdrop = dfsignals.drop(columns=["open" ,"high" , "low" , "khigh","dhigh","kmed" ,"dmed","klow","dlow"])
    dfsignalsout = dfsignalsdrop[(dfsignalsdrop['state'] == 'out')]

    # elimino a culuna stpl de dfstoploss e filtro os valores enter e out 
    dfstoplossdrop = dfstoploss.drop(columns=["stpl"]) 
    dfstoplossenterout = dfstoplossdrop[(dfstoplossdrop['state'] == 'enter') | (dfstoplossdrop['state'] == 'out')]

    # concatenar os dois df para ter o total dos signals enter e out
    dfsignalsenterout = pd.concat([dfsignalsout, dfstoplossenterout], ignore_index=True)

    # Ordenar pelo datetime e resetear o index
    dfsignalsenterout["datetime"] = pd.to_datetime(dfsignalsenterout["datetime"])
    dfsignalsenterout = dfsignalsenterout.sort_values("datetime").reset_index(drop=True)

    # limpar os out duplicados"out" por a saida anticipada do stoploss e reiniciar indice
    df = dfsignalsenterout
    cond = (df["state"] == "out")  & (df["state"].shift(1) == "out")
    dfsignalsentoutclean = df[~cond].reset_index(drop=True)
    return dfsignalsentoutclean

In [34]:
dfsignalsentoutclean = index_dataframe (dfsignals, dfstoploss)
display (dfsignalsentoutclean)

               datetime    close  longbuylow  longbuymed  longbuyhigh  state
0   2006-04-05 13:00:00   5.9816           1           1            1  enter
1   2006-04-06 15:00:00   5.8889           1           0            0    out
2   2006-04-20 14:00:00   5.8425           1           1            1  enter
3   2006-04-27 14:00:00   5.6802           1           1            0    out
4   2006-04-28 09:00:00   5.7421           1           1            0  enter
..                  ...      ...         ...         ...          ...    ...
467 2024-03-15 16:00:00  21.6673           1           1            1    out
468 2024-03-18 07:00:00  22.1850           1           1            1  enter
469 2024-03-18 09:00:00  21.6812           1           1            1    out
470 2024-03-18 11:00:00  22.3236           1           1            1  enter
471 2024-03-26 14:00:00  23.8858           1           0            0    out

[472 rows x 6 columns]

Index ,Trade, Index sin comission

In [36]:
#%%timeit
def index_trade(dfsignalsenteroutclean):
    df = dfsignalsentoutclean
    df ["index_sc"] = 100. 
    df ["trade"] = 0.
    df ["index"] = 100. *(1-comission) 
    for i in range(1, len(df)):      
                       
        if  df.loc[i, "state"] == "out" :
            df.loc[i, "index_sc"] = (((df.loc[i,"close"]-df.loc[i-1,"close"])/df.loc[i-1,"close"])+1)* df.loc[i-1,"index_sc"]
            df.loc[i, "index"] = df.loc[i, "index_sc"]* (1-comission)
            df.loc[i, "trade"] = (df.loc[i,"close"]-df.loc[i-1,"close"])/df.loc[i-1,"close"]
            
        if  df.loc[i, "state"] == "enter" :        
            df.loc[i, "index_sc"] =  df.loc[i-1, "index_sc"]
            df.loc[i, "index"] = df.loc[i, "index_sc"]* (1-comission)
    dfindex = df
    return dfindex

In [38]:
dfindex = index_trade(dfsignalsentoutclean)
display (dfindex.head(10))

,datetime,close,longbuylow,longbuymed,longbuyhigh,state,index_sc,trade,index
0,2006-04-05 13:00:00,5.9816,1,1,1,enter,100.000000,0.000000,99.650000
1,2006-04-06 15:00:00,5.8889,1,0,0,out,98.450247,-0.015498,98.105672
2,2006-04-20 14:00:00,5.8425,1,1,1,enter,98.450247,0.000000,98.105672
3,2006-04-27 14:00:00,5.6802,1,1,0,out,95.715378,-0.027779,95.380374
4,2006-04-28 09:00:00,5.7421,1,1,0,enter,95.715378,0.000000,95.380374
5,2006-04-28 11:00:00,5.7111,1,0,1,out,95.198637,-0.005399,94.865442
6,2006-05-05 15:00:00,5.8348,1,1,1,enter,95.198637,0.000000,94.865442
7,2006-05-11 11:00:00,5.6339,1,1,0,out,91.920820,-0.034431,91.599097
8,2006-05-26 15:00:00,4.9460,1,1,1,enter,91.920820,0.000000,91.599097
9,2006-05-30 10:00:00,4.7683,1,1,0,out,88.618287,-0.035928,88.308123

stop drawdawn

In [41]:
#%%timeit
def stop_drawdawn (dfindex, drawmax):
    df = dfindex
    df = df.copy()
    df["datetime"] = pd.to_datetime(df["datetime"])
    df["index"] = pd.to_numeric(df["index"], errors="coerce")

    estado_corrigido = []
    pico_atual = df.loc[0, "index"]

    for i in range(len(df)):
        valor_index = df.loc[i, "index"]
        estado = df.loc[i, "state"]

        # Atualiza pico se houve recuperação
        if valor_index > pico_atual:
            pico_atual = valor_index

        # Calcula drawdown
        if pico_atual > 0:
            drawdown = (valor_index - pico_atual) / pico_atual
        else:
            drawdown = 0

        # Verifica se deve aplicar stopsys
        if estado == "out" and drawdown < drawmax:
            estado = "stopsys"
            pico_atual = valor_index  # reinicia ciclo a partir desse ponto

        estado_corrigido.append(estado)
    df["state"] = estado_corrigido
    dfindexdrawdawn = df
    return dfindexdrawdawn

In [43]:
dfindexdrawdawn = stop_drawdawn(dfindex, drawmax)
display(dfindexdrawdawn)

,datetime,close,longbuylow,longbuymed,longbuyhigh,state,index_sc,trade,index
0,2006-04-05 13:00:00,5.9816,1,1,1,enter,100.000000,0.000000,99.650000
1,2006-04-06 15:00:00,5.8889,1,0,0,out,98.450247,-0.015498,98.105672
2,2006-04-20 14:00:00,5.8425,1,1,1,enter,98.450247,0.000000,98.105672
3,2006-04-27 14:00:00,5.6802,1,1,0,out,95.715378,-0.027779,95.380374
4,2006-04-28 09:00:00,5.7421,1,1,0,enter,95.715378,0.000000,95.380374
...,...,...,...,...,...,...,...,...,...
467,2024-03-15 16:00:00,21.6673,1,1,1,out,133.401223,-0.016366,132.934319
468,2024-03-18 07:00:00,22.1850,1,1,1,enter,133.401223,0.000000,132.934319
469,2024-03-18 09:00:00,21.6812,1,1,1,out,130.371809,-0.022709,129.915508
470,2024-03-18 11:00:00,22.3236,1,1,1,enter,130.371809,0.000000,129.915508
471,2024-03-26 14:00:00,23.8858,1,0,0,out,139.495196,0.069980,139.006963

Metricas

Tir anualizada Total e desvio padrão das Tir anuales Max e MIn
dataini = '2015-04-03 19:30:00'
datafim = '2019-04-03 19:30:00'

In [47]:
#%%timeit
def dataframe_tir (dfindexdrawdawn):
    dftir = dfindexdrawdawn[['datetime', 'state', 'index']]
    return dftir

In [57]:
dftir = dataframe_tir (dfindexdrawdawn)
display(dftir)

               datetime  state       index
0   2006-04-05 13:00:00  enter   99.650000
1   2006-04-06 15:00:00    out   98.105672
2   2006-04-20 14:00:00  enter   98.105672
3   2006-04-27 14:00:00    out   95.380374
4   2006-04-28 09:00:00  enter   95.380374
..                  ...    ...         ...
467 2024-03-15 16:00:00    out  132.934319
468 2024-03-18 07:00:00  enter  132.934319
469 2024-03-18 09:00:00    out  129.915508
470 2024-03-18 11:00:00  enter  129.915508
471 2024-03-26 14:00:00    out  139.006963

[472 rows x 3 columns]

In [59]:


# Exemplo do DataFrame original
df = dftir
dataini = pd.to_datetime(dataini)
datafim = pd.to_datetime(datafim)

# Lista para novos registros
novos_registros = []

# Verifica se dataini deve ser adicionado
if dataini < df.iloc[0]['datetime']:
    novos_registros.append({
        'datetime': dataini,
        'state': '',
        'index': df.iloc[0]['index']
    })

# Verifica se datafim deve ser adicionado
if datafim > df.iloc[-1]['datetime']:
    novos_registros.append({
        'datetime': datafim,
        'state': '',
        'index': df.iloc[-1]['index']
    })

# Adiciona os registros e ordena
df = pd.concat([pd.DataFrame(novos_registros), df], ignore_index=True)
df = df.sort_values(by='datetime').reset_index(drop=True)

In [61]:
display ( df)

               datetime  state       index
0   2004-04-03 19:30:00          99.650000
1   2006-04-05 13:00:00  enter   99.650000
2   2006-04-06 15:00:00    out   98.105672
3   2006-04-20 14:00:00  enter   98.105672
4   2006-04-27 14:00:00    out   95.380374
..                  ...    ...         ...
469 2024-03-18 07:00:00  enter  132.934319
470 2024-03-18 09:00:00    out  129.915508
471 2024-03-18 11:00:00  enter  129.915508
472 2024-03-26 14:00:00    out  139.006963
473 2024-04-03 19:30:00         139.006963

[474 rows x 3 columns]

In [63]:


# Determina os anos, excluindo o último ano
ano_inicial = df['datetime'].min().year
ano_final = (df['datetime'].max().year)

# Gera os anos do intervalo EXCLUINDO o último ano
anos_validos = range(ano_inicial, ano_final-1 )  # << ajuste aqui

# Lista para os novos registros
novos_registros = []

for ano in anos_validos:
    fim_do_ano = pd.to_datetime(f'{ano}-12-31 23:59:59')
    df_antes = df[df['datetime'] < fim_do_ano]
    if not df_antes.empty:
        index_valor = df_antes.iloc[-1]['index']
        novos_registros.append({
            'datetime': fim_do_ano,
            'state': '',
            'index': index_valor
        })

# Adiciona e organiza
df = pd.concat([df, pd.DataFrame(novos_registros)], ignore_index=True)
df = df.sort_values('datetime').reset_index(drop=True)

In [70]:
#pd.set_option('display.max_rows', None)
display (ano_final)
display (anos_validos)
display (df)

2024

range(2004, 2023)

               datetime    state       index
0   2004-04-03 19:30:00            99.650000
1   2004-12-31 23:59:59            99.650000
2   2005-12-31 23:59:59            99.650000
3   2006-04-05 13:00:00    enter   99.650000
4   2006-04-06 15:00:00      out   98.105672
5   2006-04-20 14:00:00    enter   98.105672
6   2006-04-27 14:00:00      out   95.380374
7   2006-04-28 09:00:00    enter   95.380374
8   2006-04-28 11:00:00      out   94.865442
9   2006-05-05 15:00:00    enter   94.865442
10  2006-05-11 11:00:00      out   91.599097
11  2006-05-26 15:00:00    enter   91.599097
12  2006-05-30 10:00:00  stopsys   88.308123
13  2006-05-31 11:00:00    enter   88.308123
14  2006-06-02 09:00:00      out   89.976249
15  2006-10-03 09:00:00    enter   89.976249
16  2006-10-17 09:00:00      out   93.363838
17  2006-10-23 12:00:00    enter   93.363838
18  2006-11-01 14:00:00      out  102.076315
19  2006-11-09 09:00:00    enter  102.076315
20  2006-11-10 10:00:00      out   99.486610
21  2006-12-04 11:00:00    enter   99.486610
22  2006-12-14 12:00:00      out  107.091154
23  2006-12-18 14:00:00    enter  107.091154
24  2006-12-22 15:00:00      out  107.091154
25  2006-12-31 23:59:59           107.091154
26  2007-01-03 11:00:00    enter  107.091154
27  2007-01-03 14:00:00      out  103.928839
28  2007-01-03 15:00:00    enter  103.928839
29  2007-01-04 09:00:00      out  101.567104
30  2007-01-17 14:00:00    enter  101.567104
31  2007-01-18 14:00:00      out   99.053805
32  2007-02-06 11:00:00    enter   99.053805
33  2007-02-27 09:00:00      out  113.051098
34  2007-12-31 23:59:59           113.051098
35  2008-03-25 16:00:00    enter  113.051098
36  2008-03-26 09:00:00      out  110.557830
37  2008-03-26 15:00:00    enter  110.557830
38  2008-03-27 09:00:00      out  109.734872
39  2008-03-27 11:00:00    enter  109.734872
40  2008-03-28 09:00:00      out  107.946802
41  2008-03-28 15:00:00    enter  107.946802
42  2008-03-28 16:00:00      out  106.861113
43  2008-04-04 11:00:00    enter  106.861113
44  2008-04-15 09:00:00      out  104.664154
45  2008-04-15 10:00:00    enter  104.664154
46  2008-04-15 12:00:00      out  103.269781
47  2008-04-15 13:00:00    enter  103.269781
48  2008-04-15 14:00:00      out  102.651650
49  2008-05-06 10:00:00    enter  102.651650
50  2008-05-07 09:00:00  stopsys  100.517900
51  2008-05-19 11:00:00    enter  100.517900
52  2008-05-23 09:00:00      out   98.132595
53  2008-12-31 23:59:59            98.132595
54  2009-06-04 08:00:00    enter   98.132595
55  2009-06-04 09:00:00      out   90.994770
56  2009-06-10 09:00:00    enter   90.994770
57  2009-06-10 11:00:00  stopsys   89.604877
58  2009-06-10 15:00:00    enter   89.604877
59  2009-06-11 14:00:00      out   88.502520
60  2009-06-29 10:00:00    enter   88.502520
61  2009-06-29 15:00:00      out   85.831529
62  2009-06-30 09:00:00    enter   85.831529
63  2009-07-02 09:00:00  stopsys   79.739432
64  2009-07-02 11:00:00    enter   79.739432
65  2009-07-02 12:00:00      out   79.371721
66  2009-07-06 09:00:00    enter   79.371721
67  2009-07-08 11:00:00      out   76.262805
68  2009-07-17 12:00:00    enter   76.262805
69  2009-07-23 16:00:00      out   76.702335
70  2009-08-03 15:00:00    enter   76.702335
71  2009-08-03 16:00:00      out   74.416086
72  2009-08-04 10:00:00    enter   74.416086
73  2009-08-13 14:00:00      out   77.031605
74  2009-08-24 12:00:00    enter   77.031605
75  2009-08-25 10:00:00      out   74.924003
76  2009-08-25 11:00:00    enter   74.924003
77  2009-08-25 14:00:00      out   73.050479
78  2009-08-26 12:00:00    enter   73.050479
79  2009-08-26 13:00:00  stopsys   71.760536
80  2009-08-27 09:00:00    enter   71.760536
81  2009-08-27 11:00:00      out   70.859972
82  2009-08-27 12:00:00    enter   70.859972
83  2009-08-28 15:00:00      out   69.968477
84  2009-08-31 15:00:00    enter   69.968477
85  2009-09-01 11:00:00      out   68.063628
86  2009-09-14 10:00:00    enter   68.063628
87  2009-09-23 10:00:00      out   76.060493
88  2009-09-30 16:00:00    enter   76.060493
89  2009-10-01 10:00:00      out   76.545274
90  2009-10-08 12:00:00    enter   76.545274
91  2009-10-16 12:00:00      out   76.834160
92  2009-10-23 10:00:00    enter   76.834160
93  2009-10-23 15:00:00      out   74.767225
94  2009-10-26 09:00:00    enter   74.767225
95  2009-10-28 11:00:00      out   73.745191
96  2009-11-06 11:00:00    enter   73.745191
97  2009-11-06 14:00:00      out   71.037017
98  2009-11-06 15:00:00    enter   71.037017
99  2009-11-12 11:00:00      out   70.315678
100 2009-12-31 23:59:59            70.315678
101 2010-04-14 14:00:00    enter   70.315678
102 2010-04-16 11:00:00  stopsys   68.625734
103 2010-04-28 11:00:00    enter   68.625734
104 2010-04-30 09:00:00      out   68.907148
105 2010-05-10 16:00:00    enter   68.907148
106 2010-05-11 10:00:00      out   67.408681
107 2010-05-11 11:00:00    enter   67.408681
108 2010-05-13 09:00:00      out   65.935403
109 2010-05-13 10:00:00    enter   65.935403
110 2010-05-14 09:00:00      out   64.378667
111 2010-05-28 16:00:00    enter   64.378667
112 2010-06-07 09:00:00      out   63.219908
113 2010-08-04 16:00:00    enter   63.219908
114 2010-08-12 11:00:00      out   69.983592
115 2010-08-19 09:00:00    enter   69.983592
116 2010-08-19 10:00:00      out   67.705959
117 2010-09-01 13:00:00    enter   67.705959
118 2010-09-16 14:00:00      out   68.906174
119 2010-09-17 12:00:00    enter   68.906174
120 2010-09-27 09:00:00      out   74.265785
121 2010-10-01 09:00:00    enter   74.265785
122 2010-10-01 12:00:00      out   73.305773
123 2010-10-11 16:00:00    enter   73.305773
124 2010-10-12 10:00:00      out   72.364717
125 2010-10-25 09:00:00    enter   72.364717
126 2010-10-28 13:00:00      out   76.449402
127 2010-11-03 12:00:00    enter   76.449402
128 2010-11-11 12:00:00      out   82.440645
129 2010-12-02 09:00:00    enter   82.440645
130 2010-12-03 10:00:00      out   80.719243
131 2010-12-03 15:00:00    enter   80.719243
132 2010-12-07 11:00:00      out   80.276249
133 2010-12-31 23:59:59            80.276249
134 2011-08-04 13:00:00    enter   80.276249
135 2011-08-04 15:00:00      out   77.824184
136 2011-08-12 16:00:00    enter   77.824184
137 2011-08-16 09:00:00      out   74.921941
138 2011-08-29 12:00:00    enter   74.921941
139 2011-09-01 13:00:00  stopsys   73.293626
140 2011-12-31 23:59:59            73.293626
141 2012-09-26 14:00:00    enter   73.293626
142 2012-09-28 10:00:00      out   71.526832
143 2012-10-18 10:00:00    enter   71.526832
144 2012-10-19 09:00:00      out   69.555807
145 2012-10-19 11:00:00    enter   69.555807
146 2012-10-19 14:00:00      out   68.215669
147 2012-10-22 13:00:00    enter   68.215669
148 2012-10-22 16:00:00      out   67.856800
149 2012-11-26 09:00:00    enter   67.856800
150 2012-12-11 15:00:00      out   91.814601
151 2012-12-31 23:59:59            91.814601
152 2013-01-02 13:00:00    enter   91.814601
153 2013-01-04 14:00:00      out   91.154894
154 2013-01-28 16:00:00    enter   91.154894
155 2013-01-29 11:00:00      out   89.619159
156 2013-03-04 13:00:00    enter   89.619159
157 2013-03-20 10:00:00      out   90.411240
158 2013-08-20 16:00:00    enter   90.411240
159 2013-08-26 11:00:00      out   89.259943
160 2013-09-06 12:00:00    enter   89.259943
161 2013-09-17 10:00:00      out  104.896341
162 2013-09-18 16:00:00    enter  104.896341
163 2013-09-30 10:00:00      out  112.218414
164 2013-10-10 11:00:00    enter  112.218414
165 2013-10-17 13:00:00      out  115.078407
166 2013-10-24 11:00:00    enter  115.078407
167 2013-10-25 14:00:00      out  111.960037
168 2013-11-08 12:00:00    enter  111.960037
169 2013-11-12 15:00:00      out  109.211650
170 2013-11-13 09:00:00    enter  109.211650
171 2013-12-03 14:00:00      out  132.899466
172 2013-12-31 23:59:59           132.899466
173 2014-04-04 09:00:00    enter  132.899466
174 2014-04-04 11:00:00      out  128.101069
175 2014-04-23 12:00:00    enter  128.101069
176 2014-04-25 09:00:00      out  124.828341
177 2014-04-28 09:00:00    enter  124.828341
178 2014-04-28 10:00:00      out  123.361445
179 2014-05-07 10:00:00    enter  123.361445
180 2014-05-08 14:00:00      out  120.221432
181 2014-05-09 15:00:00    enter  120.221432
182 2014-05-12 10:00:00  stopsys  119.510352
183 2014-05-12 11:00:00    enter  119.510352
184 2014-05-12 12:00:00      out  118.541673
185 2014-05-29 16:00:00    enter  118.541673
186 2014-06-11 16:00:00      out  125.814219
187 2014-06-23 15:00:00    enter  125.814219
188 2014-06-24 12:00:00      out  122.643295
189 2014-06-25 11:00:00    enter  122.643295
190 2014-06-26 14:00:00      out  119.207453
191 2014-06-30 18:00:00    enter  119.207453
192 2014-07-15 16:00:00      out  128.126620
193 2014-07-31 10:00:00    enter  128.126620
194 2014-08-01 11:00:00      out  121.814524
195 2014-08-01 13:00:00    enter  121.814524
196 2014-08-04 09:00:00      out  119.714448
197 2014-08-04 10:00:00    enter  119.714448
198 2014-08-05 09:00:00  stopsys  115.232130
199 2014-12-19 11:00:00    enter  115.232130
200 2014-12-31 23:59:59           115.232130
201 2015-01-02 16:00:00      out  118.624634
202 2015-01-12 14:00:00    enter  118.624634
203 2015-01-23 11:00:00      out  121.250218
204 2015-02-05 10:00:00    enter  121.250218
205 2015-02-18 14:00:00      out  137.702429
206 2015-02-25 10:00:00    enter  137.702429
207 2015-02-25 14:00:00      out  132.389257
208 2015-02-25 16:00:00    enter  132.389257
209 2015-02-26 09:00:00      out  127.847711
210 2015-03-06 12:00:00    enter  127.847711
211 2015-03-20 13:00:00      out  148.897514
212 2015-04-23 10:00:00    enter  148.897514
213 2015-04-29 11:00:00      out  145.805173
214 2015-04-29 12:00:00    enter  145.805173
215 2015-04-30 09:00:00      out  144.146567
216 2015-11-03 14:00:00    enter  144.146567
217 2015-11-05 13:00:00      out  144.826312
218 2015-11-12 11:00:00    enter  144.826312
219 2015-11-23 14:00:00      out  142.300260
220 2015-12-11 16:00:00    enter  142.300260
221 2015-12-14 09:00:00      out  137.998994
222 2015-12-15 11:00:00    enter  137.998994
223 2015-12-31 23:59:59           137.998994
224 2016-01-06 16:00:00      out  144.444209
225 2016-01-26 11:00:00    enter  144.444209
226 2016-02-08 09:00:00      out  150.642130
227 2016-02-10 10:00:00    enter  150.642130
228 2016-02-10 14:00:00      out  146.543891
229 2016-02-10 15:00:00    enter  146.543891
230 2016-02-11 09:00:00      out  142.529883
231 2016-02-22 11:00:00    enter  142.529883
232 2016-02-23 12:00:00      out  139.664048
233 2016-02-23 13:00:00    enter  139.664048
234 2016-02-24 09:00:00      out  137.693474
235 2016-02-24 11:00:00    enter  137.693474
236 2016-02-25 12:00:00      out  143.516900
237 2016-03-18 10:00:00    enter  143.516900
238 2016-03-29 10:00:00      out  139.605137
239 2016-04-13 11:00:00    enter  139.605137
240 2016-04-25 11:00:00      out  142.164509
241 2016-07-14 16:00:00    enter  142.164509
242 2016-07-20 13:00:00      out  139.865988
243 2016-08-09 14:00:00    enter  139.865988
244 2016-08-11 11:00:00      out  139.111907
245 2016-11-07 15:00:00    enter  139.111907
246 2016-11-09 15:00:00  stopsys  135.267886
247 2016-12-31 23:59:59           135.267886
248 2017-02-07 12:00:00    enter  135.267886
249 2017-02-16 15:00:00      out  141.077354
250 2017-03-07 16:00:00    enter  141.077354
251 2017-03-28 10:00:00      out  162.025500
252 2017-04-06 13:00:00    enter  162.025500
253 2017-04-10 13:00:00      out  159.267689
254 2017-05-03 09:00:00    enter  159.267689
255 2017-05-12 11:00:00      out  167.998827
256 2017-05-31 13:00:00    enter  167.998827
257 2017-06-07 11:00:00      out  170.720629
258 2017-09-28 10:00:00    enter  170.720629
259 2017-10-11 12:00:00      out  180.159448
260 2017-10-17 14:00:00    enter  180.159448
261 2017-10-18 14:00:00      out  176.202189
262 2017-10-18 15:00:00    enter  176.202189
263 2017-10-19 09:00:00      out  175.135203
264 2017-10-19 10:00:00    enter  175.135203
265 2017-10-20 09:00:00      out  175.364074
266 2017-11-06 13:00:00    enter  175.364074
267 2017-11-10 12:00:00      out  171.543652
268 2017-11-10 13:00:00    enter  171.543652
269 2017-11-10 14:00:00      out  170.828605
270 2017-11-20 12:00:00    enter  170.828605
271 2017-11-30 10:00:00      out  174.793005
272 2017-12-05 12:00:00    enter  174.793005
273 2017-12-13 15:00:00      out  192.278232
274 2017-12-31 23:59:59           192.278232
275 2018-01-02 13:00:00    enter  192.278232
276 2018-01-08 12:00:00      out  191.848377
277 2018-01-18 12:00:00    enter  191.848377
278 2018-01-22 10:00:00      out  186.310566
279 2018-02-06 10:00:00    enter  186.310566
280 2018-02-07 15:00:00      out  184.962321
281 2018-02-12 14:00:00    enter  184.962321
282 2018-02-13 14:00:00      out  182.750318
283 2018-12-31 23:59:59           182.750318
284 2019-01-09 10:00:00    enter  182.750318
285 2019-01-11 16:00:00      out  181.799283
286 2019-01-23 13:00:00    enter  181.799283
287 2019-01-30 10:00:00      out  186.639925
288 2019-02-05 10:00:00    enter  186.639925
289 2019-02-06 13:00:00      out  181.726959
290 2019-03-13 19:00:00    enter  181.726959
291 2019-03-14 09:00:00  stopsys  171.387413
292 2019-03-15 12:00:00    enter  171.387413
293 2019-03-15 15:00:00      out  170.709492
294 2019-03-18 09:00:00    enter  170.709492
295 2019-03-20 12:00:00      out  165.897162
296 2019-03-20 13:00:00    enter  165.897162
297 2019-03-21 11:00:00      out  164.791721
298 2019-04-03 09:00:00    enter  164.791721
299 2019-04-03 11:00:00      out  161.101589
300 2019-04-03 13:00:00    enter  161.101589
301 2019-04-03 14:00:00      out  160.367487
302 2019-04-04 09:00:00    enter  160.367487
303 2019-04-04 11:00:00      out  159.260845
304 2019-04-04 14:00:00    enter  159.260845
305 2019-04-08 09:00:00      out  164.388083
306 2019-04-10 14:00:00    enter  164.388083
307 2019-04-11 10:00:00      out  160.994562
308 2019-04-12 08:00:00    enter  160.994562
309 2019-04-12 10:00:00      out  159.838030
310 2019-04-12 11:00:00    enter  159.838030
311 2019-04-15 14:00:00      out  165.819007
312 2019-06-24 16:00:00    enter  165.819007
313 2019-06-26 13:00:00      out  160.449706
314 2019-06-26 15:00:00    enter  160.449706
315 2019-07-01 14:00:00      out  168.684583
316 2019-07-10 08:00:00    enter  168.684583
317 2019-07-10 11:00:00      out  166.429983
318 2019-07-12 10:00:00    enter  166.429983
319 2019-07-15 11:00:00      out  160.914425
320 2019-07-30 10:00:00    enter  160.914425
321 2019-07-30 13:00:00      out  157.510837
322 2019-07-30 15:00:00    enter  157.510837
323 2019-07-31 09:00:00      out  156.966344
324 2019-07-31 13:00:00    enter  156.966344
325 2019-07-31 14:00:00  stopsys  151.870950
326 2019-12-31 23:59:59           151.870950
327 2020-06-25 16:00:00    enter  151.870950
328 2020-06-26 09:00:00      out  147.885967
329 2020-07-06 19:00:00    enter  147.885967
330 2020-07-07 09:00:00      out  141.313001
331 2020-07-08 09:00:00    enter  141.313001
332 2020-07-08 10:00:00      out  140.544387
333 2020-07-08 16:00:00    enter  140.544387
334 2020-07-08 17:00:00      out  139.150506
335 2020-07-09 07:00:00    enter  139.150506
336 2020-07-09 08:00:00      out  137.280157
337 2020-07-10 11:00:00    enter  137.280157
338 2020-07-14 16:00:00      out  138.696543
339 2020-07-16 14:00:00    enter  138.696543
340 2020-07-16 16:00:00      out  138.358193
341 2020-07-22 17:00:00    enter  138.358193
342 2020-07-29 11:00:00  stopsys  136.565683
343 2020-09-01 10:00:00    enter  136.565683
344 2020-09-02 09:00:00      out  130.838693
345 2020-09-03 09:00:00    enter  130.838693
346 2020-09-03 10:00:00      out  127.889981
347 2020-09-03 11:00:00    enter  127.889981
348 2020-09-03 14:00:00      out  127.265364
349 2020-09-03 15:00:00    enter  127.265364
350 2020-09-03 17:00:00      out  125.158614
351 2020-09-04 09:00:00    enter  125.158614
352 2020-09-04 10:00:00      out  123.934528
353 2020-09-04 11:00:00    enter  123.934528
354 2020-09-04 12:00:00  stopsys  122.394341
355 2020-09-08 11:00:00    enter  122.394341
356 2020-09-09 11:00:00      out  121.145646
357 2020-09-09 12:00:00    enter  121.145646
358 2020-09-10 08:00:00      out  117.275441
359 2020-09-10 09:00:00    enter  117.275441
360 2020-09-11 09:00:00      out  113.495042
361 2020-12-29 10:00:00    enter  113.495042
362 2020-12-31 09:00:00      out  110.699079
363 2020-12-31 10:00:00    enter  110.699079
364 2020-12-31 15:00:00  stopsys  109.944627
365 2020-12-31 23:59:59           109.944627
366 2021-01-28 11:00:00    enter  109.944627
367 2021-01-29 12:00:00      out  107.129730
368 2021-02-01 10:00:00    enter  107.129730
369 2021-02-12 12:00:00      out  112.535060
370 2021-03-19 14:00:00    enter  112.535060
371 2021-03-22 09:00:00      out  109.275104
372 2021-03-22 11:00:00    enter  109.275104
373 2021-03-22 12:00:00      out  109.204437
374 2021-04-08 14:00:00    enter  109.204437
375 2021-04-09 10:00:00      out  106.594320
376 2021-04-22 13:00:00    enter  106.594320
377 2021-04-23 13:00:00      out  106.891317
378 2021-04-27 11:00:00    enter  106.891317
379 2021-04-30 10:00:00      out  104.499876
380 2021-04-30 12:00:00    enter  104.499876
381 2021-05-03 09:00:00      out  103.965492
382 2021-05-03 10:00:00    enter  103.965492
383 2021-05-03 11:00:00      out  102.569415
384 2021-05-10 09:00:00    enter  102.569415
385 2021-05-10 10:00:00  stopsys   99.983125
386 2021-05-14 08:00:00    enter   99.983125
387 2021-05-24 16:00:00      out  101.227021
388 2021-05-28 16:00:00    enter  101.227021
389 2021-06-09 09:00:00      out  111.030849
390 2021-06-09 13:00:00    enter  111.030849
391 2021-06-10 14:00:00      out  111.788734
392 2021-07-26 10:00:00    enter  111.788734
393 2021-07-27 11:00:00      out  110.693494
394 2021-10-05 11:00:00    enter  110.693494
395 2021-10-06 09:00:00      out  107.693384
396 2021-10-06 13:00:00    enter  107.693384
397 2021-10-07 08:00:00      out  102.059126
398 2021-10-07 09:00:00    enter  102.059126
399 2021-10-08 07:00:00  stopsys   98.410552
400 2021-10-08 09:00:00    enter   98.410552
401 2021-10-27 09:00:00      out  111.034034
402 2021-11-05 15:00:00    enter  111.034034
403 2021-11-15 09:00:00      out  108.207355
404 2021-11-15 10:00:00    enter  108.207355
405 2021-11-15 13:00:00      out  108.685256
406 2021-12-31 23:59:59           108.685256
407 2022-03-21 10:00:00    enter  108.685256
408 2022-03-23 15:00:00      out  106.407708
409 2022-03-24 09:00:00    enter  106.407708
410 2022-03-29 16:00:00      out  108.643912
411 2022-05-03 16:00:00    enter  108.643912
412 2022-05-05 10:00:00      out  104.011087
413 2022-05-05 16:00:00    enter  104.011087
414 2022-05-06 09:00:00      out  100.194888
415 2022-05-06 10:00:00    enter  100.194888
416 2022-05-06 11:00:00  stopsys   99.306120
417 2022-05-06 12:00:00    enter   99.306120
418 2022-05-06 13:00:00      out   97.586813
419 2022-05-11 11:00:00    enter   97.586813
420 2022-05-12 09:00:00      out   94.938230
421 2022-05-12 16:00:00    enter   94.938230
422 2022-05-23 08:00:00      out  101.644000
423 2022-08-25 16:00:00    enter  101.644000
424 2022-08-30 14:00:00      out   99.195164
425 2022-09-09 10:00:00    enter   99.195164
426 2022-09-15 11:00:00      out   99.993833
427 2022-10-07 12:00:00    enter   99.993833
428 2022-10-11 14:00:00      out   97.151404
429 2022-10-19 14:00:00    enter   97.151404
430 2022-11-08 10:00:00      out  101.335661
431 2022-12-22 16:00:00    enter  101.335661
432 2022-12-31 23:59:59           101.335661
433 2023-01-03 13:00:00      out  110.054034
434 2023-01-06 12:00:00    enter  110.054034
435 2023-01-18 09:00:00      out  136.262061
436 2023-01-25 15:00:00    enter  136.262061
437 2023-01-27 10:00:00      out  133.141573
438 2023-02-13 14:00:00    enter  133.141573
439 2023-02-21 13:00:00      out  129.716268
440 2023-02-22 09:00:00    enter  129.716268
441 2023-02-22 10:00:00      out  127.380856
442 2023-02-22 12:00:00    enter  127.380856

In [72]:
import pandas as pd
import numpy as np

# Suponha que df seja seu DataFrame original com colunas: 'datetime', 'state', 'index'
df['datetime'] = pd.to_datetime(df['datetime'])

# ✅ Passo 1: consolidar por dia e manter o último registro
df['date'] = df['datetime'].dt.date
df_diario = df.sort_values('datetime').groupby('date', as_index=False).last()

# ✅ Passo 2: selecionar datas de fim de ano
df_fim_ano = df_diario[
    (pd.to_datetime(df_diario['date']).dt.month == 12) &
    (pd.to_datetime(df_diario['date']).dt.day == 31)
].copy()

# ✅ Passo 3: calcular TIR entre pares de fim de ano
resultados = []

for i in range(1, len(df_fim_ano)):
    dt_inicio = pd.to_datetime(df_fim_ano.iloc[i - 1]['date'])
    dt_fim = pd.to_datetime(df_fim_ano.iloc[i]['date'])
    idx_inicio = df_fim_ano.iloc[i - 1]['index']
    idx_fim = df_fim_ano.iloc[i]['index']
    dias = (dt_fim - dt_inicio).days

    if dias > 0 and idx_inicio != 0:
        tir = (idx_fim / idx_inicio) ** (365 / dias) - 1
        resultados.append({
            'datetime': dt_fim,
            'tiranual': tir
        })

# ✅ Passo 4: adicionar último intervalo incompleto
if not df_fim_ano.empty:
    dt_inicio = pd.to_datetime(df_fim_ano.iloc[-1]['date'])
    idx_inicio = df_fim_ano.iloc[-1]['index']
    dt_fim = pd.to_datetime(df_diario.iloc[-1]['date'])
    idx_fim = df_diario.iloc[-1]['index']
    dias = (dt_fim - dt_inicio).days

    if dias > 0 and idx_inicio != 0:
        tir = (idx_fim / idx_inicio) ** (365 / dias) - 1
        resultados.append({
            'datetime': dt_fim,
            'tiranual': tir
        })

# ✅ Passo 5: criar DataFrame final
dftiranual = pd.DataFrame(resultados)

In [74]:
display (dftiranual)

     datetime  tiranual
0  2005-12-31  0.000000
1  2006-12-31  0.074673
2  2007-12-31  0.055653
3  2008-12-31 -0.131627
4  2009-12-31 -0.283463
5  2010-12-31  0.141655
6  2011-12-31 -0.086982
7  2012-12-31  0.251925
8  2013-12-31  0.447476
9  2014-12-31 -0.132938
10 2015-12-31  0.197574
11 2016-12-31 -0.019737
12 2017-12-31  0.421463
13 2018-12-31 -0.049553
14 2019-12-31 -0.168970
15 2020-12-31 -0.275426
16 2021-12-31 -0.011455
17 2022-12-31 -0.067623
18 2024-04-03  0.285765

In [82]:
# Supondo que dftiranual tenha uma coluna 'tiranual'

tir_max = dftiranual['tiranual'].max()
tir_min = dftiranual['tiranual'].min()
tir_std = dftiranual['tiranual'].std()

# Exibindo os resultados formatados

print(f"🔼 Máximo da TIR: {tir_max:.6%}")
print(f"🔽 Mínimo da TIR: {tir_min:.6%}")
print(f"📐 Desvio padrão da TIR: {tir_std:.6%}")

🔼 Máximo da TIR: 44.747637%
🔽 Mínimo da TIR: -28.346256%
📐 Desvio padrão da TIR: 21.128108%

In [88]:
def calcular_tir_total_anualizada(df):
    # Garante que datetime está no formato certo
    df['datetime'] = pd.to_datetime(df['datetime'])

    # Filtra enter e out
    df_enter = df[df['state'] == 'enter']
    df_out = df[df['state'] == 'out']

    # Verificação
    if df_enter.empty or df_out.empty:
        return None

    # Índice inicial e final
    idx_inicio = df_enter.iloc[0]['index']
    idx_fim = df_out.iloc[-1]['index']

    # Período completo entre primeira e última data do DataFrame
    dt_inicio_total = df['datetime'].min()
    dt_fim_total = df['datetime'].max()
    dias_total = (dt_fim_total - dt_inicio_total).days

    # Validação
    if dias_total <= 0 or idx_inicio == 0:
        return None

    # TIR anualizada com base no período total do df
    tir_anual = (idx_fim / idx_inicio) ** (365 / dias_total) - 1

    return {
        'data_inicio_real': dt_inicio_total,
        'data_fim_real': dt_fim_total,
        'index_inicio': idx_inicio,
        'index_fim': idx_fim,
        'dias_total': dias_total,
        'tir_anualizada': tir_anual
    }

In [90]:
resultado = calcular_tir_total_anualizada(df)

if resultado:
    print(f"📍 Período total do DataFrame: {resultado['data_inicio_real']} → {resultado['data_fim_real']}")
    print(f"📈 Índice inicial (enter): {resultado['index_inicio']:.6f}")
    print(f"📈 Índice final   (out)  : {resultado['index_fim']:.6f}")
    print(f"📅 Dias no período total: {resultado['dias_total']}")
    print(f"📊 TIR anualizada (base no período total): {resultado['tir_anualizada']:.6%}")
else:
    print("⚠️ Dados insuficientes para calcular a TIR.")

📍 Período total do DataFrame: 2004-04-03 19:30:00 → 2024-04-03 19:30:00
📈 Índice inicial (enter): 99.650000
📈 Índice final   (out)  : 139.006963
📅 Dias no período total: 7305
📊 TIR anualizada (base no período total): 1.677068%

In [77]:
def datas_drawdown_max(df):
    df = df.copy()
    df = df[df["index"].notna()]
    df["datetime"] = pd.to_datetime(df["datetime"])

    # Série com índice acumulado
    acumulado = df["index"]
    pico = acumulado.cummax()
    drawdown = acumulado - pico

    # Índice do drawdown máximo
    idx_vale = drawdown.idxmin()
    idx_pico = (acumulado[:idx_vale]).idxmax()
    idx_trademin = df["trade"].idxmin()


    # Datas correspondentes
    data_pico = df.loc[idx_pico, "datetime"]
    data_vale = df.loc[idx_vale, "datetime"]
    data_trademin = df.loc[idx_trademin, "datetime"]

    # Diferença percentual
    valor_pico = df.loc[idx_pico, "index"]
    valor_vale = df.loc[idx_vale, "index"]
    drawdown_pct = ((valor_vale - valor_pico) / valor_pico) * 100
    trademin = df["trade"].min()
    
    return pd.Series({
        "Data do Pico": data_pico.strftime("%Y-%m-%d %H:%M"),
        "Data do Vale": data_vale.strftime("%Y-%m-%d %H:%M"),
        "Valor do Pico": round(valor_pico, 2),
        "Valor do Vale": round(valor_vale, 2),
        "Drawdown Máximo (%)": f"{drawdown_pct:.2f}%",
        "Màxima perdida por trade": f"{df["trade"].min()*100 :.2f}%",
        "Data do Max Loser Trade": data_trademin.strftime("%Y-%m-%d %H:%M"),
    })

In [79]:
resultado_datas = datas_drawdown_max(df)
print(resultado_datas)

Data do Pico                2019-07-01 14:00
Data do Vale                2022-05-12 09:00
Valor do Pico                          102.0
Valor do Vale                          57.41
Drawdown Máximo (%)                  -43.72%
Màxima perdida por trade              -5.23%
Data do Max Loser Trade     2021-10-07 08:00
dtype: object

In [173]:
def estatisticas_trades(df):
    df = df.copy()
    trades = df["trade"].dropna()

    positivos = trades[trades > 0]
    negativos = trades[trades < 0]

    # Porcentagem de positivos
    porcentagem_pos = (len(positivos) / len(trades)) * 100

    resultado = {
        "Total de Trades": len(trades),
        "Percentual de Trades Positivos (%)": f"{porcentagem_pos:.2f}%",
        "Média dos Trades Positivos": round(positivos.mean(), 6),
        "Desvio Padrão (Trades Positivos)": round(positivos.std(), 6),
        "Média dos Trades Negativos": round(negativos.mean(), 6),
        "Desvio Padrão (Trades Negativos)": round(negativos.std(), 6)
    }

    return pd.Series(resultado)

In [175]:
resumo_trades = estatisticas_trades(df)
print(resumo_trades)

Total de Trades                             60
Percentual de Trades Positivos (%)      16.67%
Média dos Trades Positivos            0.048725
Desvio Padrão (Trades Positivos)      0.044806
Média dos Trades Negativos           -0.016233
Desvio Padrão (Trades Negativos)      0.013479
dtype: object

In [85]:
def ranking_drawdowns_puros(df, coluna="index", top_n=5):
    df = df.copy()
    df["datetime"] = pd.to_datetime(df["datetime"])
    serie = df[coluna].dropna().reset_index(drop=True)
    datas = df["datetime"].reset_index(drop=True)

    drawdowns = []

    pico_idx = 0
    pico = serie[0]
    vale_idx = None
    valor_vale = None
    max_dd = 0

    for i in range(1, len(serie)):
        if serie[i] > pico:
            # Se recuperou acima do último pico: salvar ciclo anterior
            if vale_idx is not None and max_dd < 0:
                drawdowns.append({
                    "Data Pico": datas[pico_idx],
                    "Valor Pico": pico,
                    "Data Vale": datas[vale_idx],
                    "Valor Vale": valor_vale,
                    "Drawdown (%)": round(max_dd * 100, 2)
                })

            # Novo pico inicia novo ciclo
            pico = serie[i]
            pico_idx = i
            vale_idx = None
            max_dd = 0
        else:
            dd = (serie[i] - pico) / pico
            if dd < max_dd:
                max_dd = dd
                vale_idx = i
                valor_vale = serie[i]

    # Salva último ciclo, se aplicável
    if vale_idx is not None and max_dd < 0:
        drawdowns.append({
            "Data Pico": datas[pico_idx],
            "Valor Pico": pico,
            "Data Vale": datas[vale_idx],
            "Valor Vale": valor_vale,
            "Drawdown (%)": round(max_dd * 100, 2)
        })

    # Retorna os top N
    df_resultado = pd.DataFrame(drawdowns)
    return df_resultado.sort_values("Drawdown (%)").head(top_n).reset_index(drop=True)

In [87]:
ranking_drawdowns_puros(df, coluna="index", top_n=5)

,Data Pico,Valor Pico,Data Vale,Valor Vale,Drawdown (%)
0,2019-07-01 14:00:00,102.004024,2022-05-12 09:00:00,57.409405,-43.72
1,2019-04-03 09:00:00,99.650000,2019-04-04 11:00:00,96.305464,-3.36
2,2019-04-15 14:00:00,100.271202,2019-06-26 13:00:00,97.024371,-3.24

In [89]:
def estatisticas_drawdowns_puros(df, coluna="index"):
    df = df.copy()
    df["datetime"] = pd.to_datetime(df["datetime"])
    serie = df[coluna].dropna().reset_index(drop=True)
    datas = df["datetime"].reset_index(drop=True)

    drawdowns = []

    pico_idx = 0
    pico = serie[0]
    vale_idx = None
    valor_vale = None
    max_dd = 0

    for i in range(1, len(serie)):
        if serie[i] > pico:
            if vale_idx is not None and max_dd < 0:
                drawdowns.append(max_dd * 100)  # salva como porcentagem
            # novo ciclo
            pico = serie[i]
            pico_idx = i
            max_dd = 0
            vale_idx = None
        else:
            dd = (serie[i] - pico) / pico
            if dd < max_dd:
                max_dd = dd
                vale_idx = i
                valor_vale = serie[i]

    # salva último ciclo, se houver
    if vale_idx is not None and max_dd < 0:
        drawdowns.append(max_dd * 100)

    # série com drawdowns reais
    serie_dd = pd.Series(drawdowns)

    estatisticas = {
        "Total de Drawdowns": len(drawdowns),
        "Média dos Drawdowns (%)": round(serie_dd.mean(), 2),
        "Desvio Padrão (%)": round(serie_dd.std(), 2),
        "Drawdown Máximo (%)": round(serie_dd.min(), 2),
        "Drawdown Mínimo (%)": round(serie_dd.max(), 2)
    }

    return pd.Series(estatisticas)

In [91]:
resumo_dd_puros = estatisticas_drawdowns_puros(df)
print(resumo_dd_puros)

Total de Drawdowns          3.00
Média dos Drawdowns (%)   -16.77
Desvio Padrão (%)          23.34
Drawdown Máximo (%)       -43.72
Drawdown Mínimo (%)        -3.24
dtype: float64

In [177]:
def estatistica_periodos_estaticos_em_dias(df, coluna="index_sc"):
    df = df.copy()
    df["datetime"] = pd.to_datetime(df["datetime"])
    df = df[df[coluna].notna()].reset_index(drop=True)

    variacao = df[coluna].diff()
    grupos = (variacao != 0).cumsum()

    agrupado = df.groupby(grupos)
    periodos_estaticos = []

    for _, grupo in agrupado:
        if len(grupo) > 1 and grupo[coluna].nunique() == 1:
            duracao_dias = (grupo["datetime"].iloc[-1] - grupo["datetime"].iloc[0]).days
            periodos_estaticos.append({
                "Valor index": grupo[coluna].iloc[0],
                "Data Início": grupo["datetime"].iloc[0],
                "Data Fim": grupo["datetime"].iloc[-1],
                "Duração (dias)": duracao_dias,
                "Número de Registros": len(grupo)
            })

    df_resultado = pd.DataFrame(periodos_estaticos)

    if df_resultado.empty:
        resumo = {
            "Total de Períodos Estáticos": 0,
            "Duração Média (dias)": 0,
            "Maior Duração (dias)": 0,
            "Data do Maior Período": {"Data Início": None, "Data Fim": None}
        }
    else:
        resumo = {
            "Total de Períodos Estáticos": len(df_resultado),
            "Duração Média (dias)": round(df_resultado["Duração (dias)"].mean(), 2),
            "Maior Duração (dias)": df_resultado["Duração (dias)"].max(),
            "Data do Maior Período": df_resultado.loc[df_resultado["Duração (dias)"].idxmax(), ["Data Início", "Data Fim"]].to_dict()
        }

    return df_resultado, pd.Series(resumo)

In [179]:
df_periodos, estatisticas = estatistica_periodos_estaticos_em_dias(df)
display(df_periodos)
display(estatisticas)

,Valor index,Data Início,Data Fim,Duração (dias),Número de Registros
0,101.833293,2016-04-25 11:00:00,2016-07-14 16:00:00,80,2
1,100.186849,2016-07-20 13:00:00,2016-08-09 14:00:00,20,2
2,99.646697,2016-08-11 11:00:00,2016-11-07 15:00:00,88,2
3,96.893201,2016-11-09 15:00:00,2017-02-07 12:00:00,89,2
4,101.054558,2017-02-16 15:00:00,2017-03-07 16:00:00,19,2
5,116.059841,2017-03-28 10:00:00,2017-04-06 13:00:00,9,2
6,114.084405,2017-04-10 13:00:00,2017-05-03 09:00:00,22,2
7,120.338571,2017-05-12 11:00:00,2017-05-31 13:00:00,19,2
8,122.288214,2017-06-07 11:00:00,2017-09-28 10:00:00,112,2
9,129.049297,2017-10-11 12:00:00,2017-10-17 14:00:00,6,2
10,126.214689,2017-10-18 14:00:00,2017-10-18 15:00:00,0,2
11,125.450400,2017-10-19 09:00:00,2017-10-19 10:00:00,0,2
12,125.614342,2017-10-20 09:00:00,2017-11-06 13:00:00,17,2
13,122.877751,2017-11-10 12:00:00,2017-11-10 13:00:00,0,2
14,122.365558,2017-11-10 14:00:00,2017-11-20 12:00:00,9,2
15,125.205282,2017-11-30 10:00:00,2017-12-05 12:00:00,5,2
16,137.730055,2017-12-13 15:00:00,2018-01-02 13:00:00,19,2
17,137.422148,2018-01-08 12:00:00,2018-01-18 12:00:00,10,2
18,133.455380,2018-01-22 10:00:00,2018-02-06 10:00:00,15,2
19,132.489624,2018-02-07 15:00:00,2018-02-12 14:00:00,4,2
20,130.905153,2018-02-13 14:00:00,2019-01-09 10:00:00,329,2
21,130.223921,2019-01-11 16:00:00,2019-01-23 13:00:00,11,2
22,133.691302,2019-01-30 10:00:00,2019-02-05 10:00:00,6,2
23,130.172115,2019-02-06 13:00:00,2019-03-13 19:00:00,35,2
24,122.765836,2019-03-14 09:00:00,2019-03-15 12:00:00,1,2
25,122.280237,2019-03-15 15:00:00,2019-03-18 09:00:00,2,2
26,118.833136,2019-03-20 12:00:00,2019-03-20 13:00:00,0,2
27,118.041302,2019-03-21 11:00:00,2019-04-03 09:00:00,12,2
28,115.398038,2019-04-03 11:00:00,2019-04-03 13:00:00,0,2

Total de Períodos Estáticos                                                   29
Duração Média (dias)                                                       32.38
Maior Duração (dias)                                                         329
Data do Maior Período          {'Data Início': 2018-02-13 14:00:00, 'Data Fim...
dtype: object